#include <QtTest>
#include "core/database.h"
#include "core/pos_service.h"
#include "core/inventory_service.h"
#include "core/barcode_service.h"
#include "core/supplier_service.h"
#include "core/purchase_service.h"
#include "core/payment_service.h"
#include "core/shift_service.h"
#include "core/return_service.h"
#include "core/cheque_service.h"
#include "core/report_service.h"
#include "core/audit_service.h"
#include "core/settings_service.h"
#include "core/excel_export_service.h"
#include "core/security_service.h"
#include "core/suspended_sale_service.h"
#include <filesystem>
#include <QTemporaryDir>
#include <QFile>

class PosServiceTest final : public QObject {
    Q_OBJECT
private slots:
    void saleDecrementsStockAndCreatesLedger();
    void saleRollsBackWhenStockIsInsufficient();
    void receiptCreatesBatchAndMovement();
    void saleConsumesMultipleBatchesByFefo();
    void voidCashSaleReversesCashEntry();
    void catalogAndUnitConversionsAreValidated();
    void stockControlsProduceAlertsAndHistory();
    void ean13BarcodeRulesAreEnforced();
    void supplierCrudCreatesOpeningLedger();
    void purchaseUpdatesStockAndSupplierPayableTogether();
    void customerPaymentAllocatesToInvoiceAndLedger();
    void legacySchemaIsUpgradedAndValidated();
    void cashSaleIsAttachedToShiftAndReconciles();
    void salesReturnRestoresStockAndRefundsCash();
    void purchaseReturnReducesStockAndPayable();
    void chequeRegisterTracksDueAndStatus();
    void reportsAndAuditQueriesReturnPersistedData();
    void settingsPersistAndReadValues();
    void productImportIsAtomicAndValidated();
    void excelExportProducesOpenXmlWorkbook();
    void securityPinStoresOnlySaltedHashAndVerifies();
    void suspendedSaleRoundTripsAndRemoves();
};

static void insertProduct(pos::Database& db, const QString& id, qint64 stock) {
    auto p=db.prepare("INSERT INTO products(id,name,base_unit,stock_quantity,created_at,updated_at) VALUES(?,?,?, ?,?,?)");
    p.bind(1,id);p.bind(2,"Test product");p.bind(3,"piece");p.bind(4,stock);p.bind(5,pos::utcNow());p.bind(6,pos::utcNow());p.execute();
    auto shift=db.prepare("INSERT INTO shift_sessions(id,opened_at,opening_cash_paisa,status) VALUES(?,?,?,'open')");shift.bind(1,pos::uuid());shift.bind(2,pos::utcNow());shift.bind(3,0);shift.execute();
}
void PosServiceTest::saleDecrementsStockAndCreatesLedger(){try {const auto path=std::filesystem::temp_directory_path()/("pos-sale-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid(),customer=pos::uuid();insertProduct(*db,product,20);auto c=db->prepare("INSERT INTO customers(id,name,created_at) VALUES(?,?,?)");c.bind(1,customer);c.bind(2,"Customer");c.bind(3,pos::utcNow());c.execute();pos::PosService service(db);pos::SaleRequest request{customer,{},"credit",0,0,{},{{product,{},5,10000,0,"piece"}}};const auto sale=service.completeSale(request);QVERIFY(!sale.saleId.isEmpty());auto p=db->prepare("SELECT stock_quantity FROM products WHERE id=?");p.bind(1,product);QVERIFY(p.stepRow());QCOMPARE(p.integer(0),qint64(15));auto balance=db->prepare("SELECT balance_paisa FROM customers WHERE id=?");balance.bind(1,customer);QVERIFY(balance.stepRow());QCOMPARE(balance.integer(0),qint64(50000));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::saleRollsBackWhenStockIsInsufficient(){try {const auto path=std::filesystem::temp_directory_path()/("pos-rollback-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid();insertProduct(*db,product,2);pos::PosService service(db);pos::SaleRequest request{{},{},"cash",0,0,{},{{product,{},3,100,0,"piece"}}};QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.completeSale(request));auto p=db->prepare("SELECT stock_quantity FROM products WHERE id=?");p.bind(1,product);QVERIFY(p.stepRow());QCOMPARE(p.integer(0),qint64(2));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::receiptCreatesBatchAndMovement(){try {const auto path=std::filesystem::temp_directory_path()/("pos-receipt-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService service(db);const auto product=service.createProduct("Paracetamol","piece",500,800,true);service.receiveStock({product,24,500,"carton","LOT-01",QDate::currentDate().addDays(90),"Receiving"});auto batch=db->prepare("SELECT quantity_remaining FROM batches WHERE product_id=?");batch.bind(1,product);QVERIFY(batch.stepRow());QCOMPARE(batch.integer(0),qint64(24));auto movement=db->prepare("SELECT balance_after FROM stock_movements WHERE product_id=?");movement.bind(1,product);QVERIFY(movement.stepRow());QCOMPARE(movement.integer(0),qint64(24));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::saleConsumesMultipleBatchesByFefo(){try {const auto path=std::filesystem::temp_directory_path()/("pos-fefo-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService inventory(db);const auto product=inventory.createProduct("Vaccine","piece",10,25,true);inventory.receiveStock({product,3,10,"piece","EARLY",QDate::currentDate().addDays(4),"Receiving"});inventory.receiveStock({product,4,10,"piece","LATE",QDate::currentDate().addDays(30),"Receiving"});pos::PosService sales(db);sales.completeSale({{}, {}, "cash", 125, 0, {}, {{product,{},5,25,0,"piece"}}});auto batches=db->prepare("SELECT batch_no,quantity_remaining FROM batches WHERE product_id=? ORDER BY expiry_date");batches.bind(1,product);QVERIFY(batches.stepRow());QCOMPARE(batches.integer(1),qint64(0));QVERIFY(batches.stepRow());QCOMPARE(batches.integer(1),qint64(2));auto items=db->prepare("SELECT COUNT(*) FROM sale_items");QVERIFY(items.stepRow());QCOMPARE(items.integer(0),qint64(2));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::voidCashSaleReversesCashEntry(){try {const auto path=std::filesystem::temp_directory_path()/("pos-void-cash-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid();insertProduct(*db,product,2);pos::PosService service(db);const auto sale=service.completeSale({{}, {}, "cash", 100, 0, {}, {{product,{},1,100,0,"piece"}}});service.voidSale(sale.saleId,"Customer cancelled","Manager");auto cash=db->prepare("SELECT SUM(CASE WHEN type='cash_in' THEN amount_paisa ELSE -amount_paisa END) FROM cash_transactions WHERE sale_id=?");cash.bind(1,sale.saleId);QVERIFY(cash.stepRow());QCOMPARE(cash.integer(0),qint64(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::catalogAndUnitConversionsAreValidated(){try {const auto path=std::filesystem::temp_directory_path()/("pos-catalog-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService service(db);const auto category=service.createCategory("Medicine");const auto brand=service.createBrand("Nexora");QVERIFY(!service.createUnit("Piece","pc").isEmpty());pos::ProductDefinition product{"Syrup","SYR-01","1234567890123",category,brand,{},"piece",100,150,125,110,10,true,false,"C:/images/syrup.png"};const auto productId=service.createProduct(product);service.setUnitConversions(productId,{{"carton",24},{"box",6}});QCOMPARE(service.toBaseQuantity(productId,"carton",2),qint64(48));QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.setUnitConversions(productId,{{"broken",0}}));product.retailPrice=175;service.updateProduct(productId,product);auto updated=db->prepare("SELECT retail_price_paisa,image_path FROM products WHERE id=?");updated.bind(1,productId);QVERIFY(updated.stepRow());QCOMPARE(updated.integer(0),qint64(175));QCOMPARE(updated.text(1),QString("C:/images/syrup.png"));service.archiveProduct(productId);QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.toBaseQuantity(productId,"carton",1));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::stockControlsProduceAlertsAndHistory(){try {const auto path=std::filesystem::temp_directory_path()/("pos-stock-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService service(db);pos::ProductDefinition product{"Milk",{}, {}, {}, {},{},"piece",100,150,0,0,10,true,false,{}};const auto id=service.createProduct(product);service.receiveStock({id,20,100,"piece","DUE",QDate::currentDate().addDays(3),"Stock"});auto batch=db->prepare("SELECT id FROM batches WHERE product_id=?");batch.bind(1,id);QVERIFY(batch.stepRow());service.adjustStock({id,batch.text(0),-12,"damaged","Broken seal","Manager"});QCOMPARE(service.lowStock().size(),qsizetype(1));QCOMPARE(service.nearExpiry(QDate::currentDate().addDays(7)).size(),qsizetype(1));QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.adjustStock({id,batch.text(0),-20,"lost","Impossible","Manager"}));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::ean13BarcodeRulesAreEnforced(){pos::BarcodeService service;QCOMPARE(service.generateEan13("590123412345"),QString("5901234123457"));QVERIFY(service.isValidEan13("5901234123457"));QVERIFY(!service.isValidEan13("5901234123458"));QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.generateEan13("ABC"));}
void PosServiceTest::supplierCrudCreatesOpeningLedger(){try{const auto path=std::filesystem::temp_directory_path()/("supplier-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::SupplierService service(db);const auto id=service.create({{},"Acme", "Ali", "0300", "Lahore", 12000, false});auto supplier=service.find(id);QCOMPARE(supplier.name,QString("Acme"));QCOMPARE(supplier.openingBalance,qint64(12000));const auto entries=service.ledger(id);QCOMPARE(entries.size(),qsizetype(1));QCOMPARE(entries.first().debit,qint64(12000));auto ledger=db->prepare("SELECT balance_paisa FROM supplier_ledger WHERE supplier_id=?");ledger.bind(1,id);QVERIFY(ledger.stepRow());QCOMPARE(ledger.integer(0),qint64(12000));supplier.name="Acme Updated";service.update(supplier);QCOMPARE(service.find(id).name,QString("Acme Updated"));service.archive(id);QVERIFY(service.find(id).archived);}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::purchaseUpdatesStockAndSupplierPayableTogether(){try{const auto path=std::filesystem::temp_directory_path()/("purchase-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService inventory(db);const auto product=inventory.createProduct("Rice","kg",9000,11000,false);pos::SupplierService suppliers(db);const auto supplier=suppliers.create({{},"Wholesale Supplier",{}, {}, {}, 0, false});pos::PurchaseService purchases(db);const auto purchase=purchases.completePurchase({supplier,{},"cash",10000,0,0,{},{{product,10,1000,0,0,"kg",{}, {}}}});QVERIFY(!purchase.purchaseId.isEmpty());auto stock=db->prepare("SELECT stock_quantity FROM products WHERE id=?");stock.bind(1,product);QVERIFY(stock.stepRow());QCOMPARE(stock.integer(0),qint64(10));auto balance=db->prepare("SELECT balance_paisa FROM suppliers WHERE id=?");balance.bind(1,supplier);QVERIFY(balance.stepRow());QCOMPARE(balance.integer(0),qint64(0));auto cash=db->prepare("SELECT SUM(amount_paisa) FROM cash_transactions");QVERIFY(cash.stepRow());QCOMPARE(cash.integer(0),qint64(10000));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::customerPaymentAllocatesToInvoiceAndLedger(){try{const auto path=std::filesystem::temp_directory_path()/("payment-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid(),customer=pos::uuid();insertProduct(*db,product,2);auto insert=db->prepare("INSERT INTO customers(id,name,created_at) VALUES(?,?,?)");insert.bind(1,customer);insert.bind(2,"Paid Customer");insert.bind(3,pos::utcNow());insert.execute();pos::PosService sales(db);const auto sale=sales.completeSale({customer,{},"credit",0,0,{},{{product,{},1,500,0,"piece"}}});pos::PaymentService payments(db);const auto result=payments.recordCustomerPayment(customer,{{sale.saleId,500}},"cash","At counter");QCOMPARE(result.total,qint64(500));auto invoice=db->prepare("SELECT due_paisa,status FROM sales WHERE id=?");invoice.bind(1,sale.saleId);QVERIFY(invoice.stepRow());QCOMPARE(invoice.integer(0),qint64(0));QCOMPARE(invoice.text(1),QString("paid"));auto balance=db->prepare("SELECT balance_paisa FROM customers WHERE id=?");balance.bind(1,customer);QVERIFY(balance.stepRow());QCOMPARE(balance.integer(0),qint64(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::legacySchemaIsUpgradedAndValidated(){try{const auto path=std::filesystem::temp_directory_path()/("legacy-schema-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->exec("CREATE TABLE schema_version(version INTEGER NOT NULL); INSERT INTO schema_version VALUES(8); CREATE TABLE customers(id TEXT PRIMARY KEY,name TEXT NOT NULL,created_at TEXT NOT NULL); CREATE TABLE sales(id TEXT PRIMARY KEY,invoice_no TEXT,customer_id TEXT,status TEXT,payment_method TEXT,subtotal_paisa INTEGER,total_paisa INTEGER,created_at TEXT); CREATE TABLE sale_items(id TEXT PRIMARY KEY,sale_id TEXT,product_id TEXT,quantity INTEGER); CREATE TABLE suppliers(id TEXT PRIMARY KEY,name TEXT,created_at TEXT); CREATE TABLE products(id TEXT PRIMARY KEY,name TEXT,base_unit TEXT,created_at TEXT,updated_at TEXT); CREATE TABLE purchases(id TEXT PRIMARY KEY,invoice_no TEXT,supplier_id TEXT,status TEXT,total_paisa INTEGER,purchased_at TEXT); CREATE TABLE cash_transactions(id TEXT PRIMARY KEY,type TEXT,amount_paisa INTEGER,created_at TEXT); CREATE TABLE cheques(id TEXT PRIMARY KEY,direction TEXT,cheque_no TEXT,amount_paisa INTEGER,due_date TEXT,status TEXT,created_at TEXT); CREATE TABLE customer_payments(id TEXT PRIMARY KEY,customer_id TEXT,method TEXT,amount_paisa INTEGER,created_at TEXT); CREATE TABLE customer_ledger(id TEXT PRIMARY KEY,customer_id TEXT,description TEXT,debit_paisa INTEGER,credit_paisa INTEGER,running_balance_paisa INTEGER,created_at TEXT); CREATE TABLE batches(id TEXT PRIMARY KEY,product_id TEXT,batch_no TEXT,quantity_remaining INTEGER,purchase_price_paisa INTEGER,created_at TEXT);");db->migrate();QStringList missing;QVERIFY2(db->isSchemaCompatible(&missing),qPrintable(missing.join(", ")));QVERIFY(missing.isEmpty());}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::cashSaleIsAttachedToShiftAndReconciles(){try{const auto path=std::filesystem::temp_directory_path()/("shift-sale-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid();insertProduct(*db,product,2);pos::PosService sales(db);const auto result=sales.completeSale({{}, {}, "cash", 500, 0, {}, {{product,{},1,500,0,"piece"}}});auto row=db->prepare("SELECT shift_id FROM sales WHERE id=?");row.bind(1,result.saleId);QVERIFY(row.stepRow());QVERIFY(!row.text(0).isEmpty());pos::ShiftService shifts(db);const auto closed=shifts.close(row.text(0),500);QCOMPARE(closed.expected,qint64(500));QCOMPARE(closed.difference,qint64(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::salesReturnRestoresStockAndRefundsCash(){try{const auto path=std::filesystem::temp_directory_path()/("sales-return-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid();insertProduct(*db,product,2);pos::PosService sales(db);const auto sale=sales.completeSale({{}, {}, "cash", 500, 0, {}, {{product,{},1,500,0,"piece"}}});auto item=db->prepare("SELECT id FROM sale_items WHERE sale_id=?");item.bind(1,sale.saleId);QVERIFY(item.stepRow());pos::ReturnService returns(db);const auto result=returns.returnSale(sale.saleId,{{item.text(0),1}},"Damaged",true);QCOMPARE(result.total,qint64(500));auto stock=db->prepare("SELECT stock_quantity FROM products WHERE id=?");stock.bind(1,product);QVERIFY(stock.stepRow());QCOMPARE(stock.integer(0),qint64(2));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::purchaseReturnReducesStockAndPayable(){try{const auto path=std::filesystem::temp_directory_path()/("purchase-return-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService inventory(db);const auto product=inventory.createProduct("Rice","kg",100,150,false);pos::SupplierService suppliers(db);const auto supplier=suppliers.create({{},"Supplier",{},{},{},0,false});pos::PurchaseService purchases(db);const auto purchase=purchases.completePurchase({supplier,{},"credit",0,0,0,{},{{product,5,100,0,0,"kg",{}, {}}}});auto item=db->prepare("SELECT id FROM purchase_items WHERE purchase_id=?");item.bind(1,purchase.purchaseId);QVERIFY(item.stepRow());pos::ReturnService returns(db);returns.returnPurchase(purchase.purchaseId,{{item.text(0),2}},"Overstock");auto stock=db->prepare("SELECT stock_quantity FROM products WHERE id=?");stock.bind(1,product);QVERIFY(stock.stepRow());QCOMPARE(stock.integer(0),qint64(3));auto balance=db->prepare("SELECT balance_paisa FROM suppliers WHERE id=?");balance.bind(1,supplier);QVERIFY(balance.stepRow());QCOMPARE(balance.integer(0),qint64(300));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::chequeRegisterTracksDueAndStatus(){try{const auto path=std::filesystem::temp_directory_path()/("cheque-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::ChequeService cheques(db);const auto id=cheques.record({{},"received",{},"CH-001","HBL",{},25000,QDate::currentDate().addDays(2)});QVERIFY(!id.isEmpty());QCOMPARE(cheques.dueBy(QDate::currentDate().addDays(2)).size(),qsizetype(1));cheques.setStatus(id,"deposited");QCOMPARE(cheques.dueBy(QDate::currentDate().addDays(2)).size(),qsizetype(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::reportsAndAuditQueriesReturnPersistedData(){try{const auto path=std::filesystem::temp_directory_path()/("report-audit-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();auto audit=db->prepare("INSERT INTO audit_log(id,action,entity_type,entity_id,detail,created_at) VALUES(?,?,?,?,?,?)");audit.bind(1,pos::uuid());audit.bind(2,"test_action");audit.bind(3,"test_entity");audit.bind(4,"entity-1");audit.bind(5,"detail");audit.bind(6,pos::utcNow());audit.execute();const auto rows=pos::AuditService(db).recent("test_action");QCOMPARE(rows.size(),qsizetype(1));QCOMPARE(rows.first().entityId,QString("entity-1"));const auto summary=pos::ReportService(db).summary(QDate::currentDate(),QDate::currentDate());QCOMPARE(summary.sales,qint64(0));QCOMPARE(summary.lowStock,qint64(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::settingsPersistAndReadValues(){try{const auto path=std::filesystem::temp_directory_path()/("settings-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::SettingsService settings(db);QCOMPARE(settings.value("business.currency","PKR"),QString("PKR"));settings.setValue("business.name","Nexora Wholesale");QCOMPARE(settings.value("business.name"),QString("Nexora Wholesale"));settings.setValue("business.name","Updated Wholesale");QCOMPARE(settings.value("business.name"),QString("Updated Wholesale"));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::productImportIsAtomicAndValidated(){try{const auto path=std::filesystem::temp_directory_path()/("product-import-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService inventory(db);const QList<pos::ProductDefinition> products={{"Imported A","SKU-A","",{}, {},{},"piece",100,150,0,0,0,false,false,{}},{"Imported B","SKU-B","",{}, {},{},"piece",200,250,0,0,0,false,false,{}}};const auto ids=inventory.importProducts(products);QCOMPARE(ids.size(),qsizetype(2));QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,inventory.importProducts({products.first(),{"Broken",{}, {},{}, {},{},"piece",-1,100,0,0,0,false,false,{}}}));auto count=db->prepare("SELECT COUNT(*) FROM products WHERE is_deleted=0");QVERIFY(count.stepRow());QCOMPARE(count.integer(0),qint64(2));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::excelExportProducesOpenXmlWorkbook(){try{const auto path=QString::fromStdString((std::filesystem::temp_directory_path()/("report-"+pos::uuid().toStdString()+".xlsx")).string());pos::ExcelExportService::writeWorkbook(path,{"Metric","Value"},{{"Sales","100"}});QFile file(path);QVERIFY(file.open(QIODevice::ReadOnly));QCOMPARE(file.read(2),QByteArray("PK"));const auto package=file.readAll();QVERIFY(package.contains("xl/worksheets/sheet1.xml"));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::securityPinStoresOnlySaltedHashAndVerifies(){try{const auto path=std::filesystem::temp_directory_path()/("security-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::SecurityService security(db);QVERIFY(!security.hasPin());QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,security.setPin("12"));security.setPin("1234");QVERIFY(security.hasPin());QVERIFY(security.verifyPin("1234"));QVERIFY(!security.verifyPin("4321"));auto stored=db->prepare("SELECT value FROM settings WHERE key='security.pin_hash'");QVERIFY(stored.stepRow());QVERIFY(!stored.text(0).contains("1234"));security.clearPin();QVERIFY(!security.hasPin());}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::suspendedSaleRoundTripsAndRemoves(){try{const auto path=std::filesystem::temp_directory_path()/("suspended-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::SuspendedSaleService service(db);const auto id=service.save({{"product-1",2,150,"piece"}});QCOMPARE(service.list().size(),qsizetype(1));const auto sale=service.load(id);QCOMPARE(sale.lines.size(),qsizetype(1));QCOMPARE(sale.lines.first().quantity,qint64(2));QCOMPARE(sale.lines.first().unitPrice,qint64(150));service.remove(id);QCOMPARE(service.list().size(),qsizetype(0));}catch(const std::exception& error){QFAIL(error.what());}}
QTEST_APPLESS_MAIN(PosServiceTest)
#include "pos_service_test.moc"
