#include <QtTest>
#include "core/database.h"
#include "core/pos_service.h"
#include "core/inventory_service.h"
#include "core/barcode_service.h"
#include "core/supplier_service.h"
#include "core/purchase_service.h"
#include "core/payment_service.h"
#include <filesystem>

class PosServiceTest final : public QObject {
    Q_OBJECT
private slots:
    void saleDecrementsStockAndCreatesLedger();
    void saleRollsBackWhenStockIsInsufficient();
    void receiptCreatesBatchAndMovement();
    void saleConsumesMultipleBatchesByFefo();
    void voidCashSaleReversesCashEntry();
    void catalogAndUnitConversionsAreValidated();
    void stockControlsProduceAlertsAndHistory();
    void ean13BarcodeRulesAreEnforced();
    void supplierCrudCreatesOpeningLedger();
    void purchaseUpdatesStockAndSupplierPayableTogether();
    void customerPaymentAllocatesToInvoiceAndLedger();
};

static void insertProduct(pos::Database& db, const QString& id, qint64 stock) {
    auto p=db.prepare("INSERT INTO products(id,name,base_unit,stock_quantity,created_at,updated_at) VALUES(?,?,?, ?,?,?)");
    p.bind(1,id);p.bind(2,"Test product");p.bind(3,"piece");p.bind(4,stock);p.bind(5,pos::utcNow());p.bind(6,pos::utcNow());p.execute();
}
void PosServiceTest::saleDecrementsStockAndCreatesLedger(){try {const auto path=std::filesystem::temp_directory_path()/("pos-sale-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid(),customer=pos::uuid();insertProduct(*db,product,20);auto c=db->prepare("INSERT INTO customers(id,name,created_at) VALUES(?,?,?)");c.bind(1,customer);c.bind(2,"Customer");c.bind(3,pos::utcNow());c.execute();pos::PosService service(db);pos::SaleRequest request{customer,{},"credit",0,0,{},{{product,{},5,10000,0,"piece"}}};const auto sale=service.completeSale(request);QVERIFY(!sale.saleId.isEmpty());auto p=db->prepare("SELECT stock_quantity FROM products WHERE id=?");p.bind(1,product);QVERIFY(p.stepRow());QCOMPARE(p.integer(0),qint64(15));auto balance=db->prepare("SELECT balance_paisa FROM customers WHERE id=?");balance.bind(1,customer);QVERIFY(balance.stepRow());QCOMPARE(balance.integer(0),qint64(50000));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::saleRollsBackWhenStockIsInsufficient(){try {const auto path=std::filesystem::temp_directory_path()/("pos-rollback-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid();insertProduct(*db,product,2);pos::PosService service(db);pos::SaleRequest request{{},{},"cash",0,0,{},{{product,{},3,100,0,"piece"}}};QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.completeSale(request));auto p=db->prepare("SELECT stock_quantity FROM products WHERE id=?");p.bind(1,product);QVERIFY(p.stepRow());QCOMPARE(p.integer(0),qint64(2));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::receiptCreatesBatchAndMovement(){try {const auto path=std::filesystem::temp_directory_path()/("pos-receipt-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService service(db);const auto product=service.createProduct("Paracetamol","piece",500,800,true);service.receiveStock({product,24,500,"carton","LOT-01",QDate::currentDate().addDays(90),"Receiving"});auto batch=db->prepare("SELECT quantity_remaining FROM batches WHERE product_id=?");batch.bind(1,product);QVERIFY(batch.stepRow());QCOMPARE(batch.integer(0),qint64(24));auto movement=db->prepare("SELECT balance_after FROM stock_movements WHERE product_id=?");movement.bind(1,product);QVERIFY(movement.stepRow());QCOMPARE(movement.integer(0),qint64(24));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::saleConsumesMultipleBatchesByFefo(){try {const auto path=std::filesystem::temp_directory_path()/("pos-fefo-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService inventory(db);const auto product=inventory.createProduct("Vaccine","piece",10,25,true);inventory.receiveStock({product,3,10,"piece","EARLY",QDate::currentDate().addDays(4),"Receiving"});inventory.receiveStock({product,4,10,"piece","LATE",QDate::currentDate().addDays(30),"Receiving"});pos::PosService sales(db);sales.completeSale({{}, {}, "cash", 125, 0, {}, {{product,{},5,25,0,"piece"}}});auto batches=db->prepare("SELECT batch_no,quantity_remaining FROM batches WHERE product_id=? ORDER BY expiry_date");batches.bind(1,product);QVERIFY(batches.stepRow());QCOMPARE(batches.integer(1),qint64(0));QVERIFY(batches.stepRow());QCOMPARE(batches.integer(1),qint64(2));auto items=db->prepare("SELECT COUNT(*) FROM sale_items");QVERIFY(items.stepRow());QCOMPARE(items.integer(0),qint64(2));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::voidCashSaleReversesCashEntry(){try {const auto path=std::filesystem::temp_directory_path()/("pos-void-cash-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid();insertProduct(*db,product,2);pos::PosService service(db);const auto sale=service.completeSale({{}, {}, "cash", 100, 0, {}, {{product,{},1,100,0,"piece"}}});service.voidSale(sale.saleId,"Customer cancelled","Manager");auto cash=db->prepare("SELECT SUM(CASE WHEN type='cash_in' THEN amount_paisa ELSE -amount_paisa END) FROM cash_transactions WHERE sale_id=?");cash.bind(1,sale.saleId);QVERIFY(cash.stepRow());QCOMPARE(cash.integer(0),qint64(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::catalogAndUnitConversionsAreValidated(){try {const auto path=std::filesystem::temp_directory_path()/("pos-catalog-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService service(db);const auto category=service.createCategory("Medicine");const auto brand=service.createBrand("Nexora");QVERIFY(!service.createUnit("Piece","pc").isEmpty());pos::ProductDefinition product{"Syrup","SYR-01","1234567890123",category,brand,{},"piece",100,150,125,110,10,true,false,"C:/images/syrup.png"};const auto productId=service.createProduct(product);service.setUnitConversions(productId,{{"carton",24},{"box",6}});QCOMPARE(service.toBaseQuantity(productId,"carton",2),qint64(48));QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.setUnitConversions(productId,{{"broken",0}}));product.retailPrice=175;service.updateProduct(productId,product);auto updated=db->prepare("SELECT retail_price_paisa,image_path FROM products WHERE id=?");updated.bind(1,productId);QVERIFY(updated.stepRow());QCOMPARE(updated.integer(0),qint64(175));QCOMPARE(updated.text(1),QString("C:/images/syrup.png"));service.archiveProduct(productId);QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.toBaseQuantity(productId,"carton",1));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::stockControlsProduceAlertsAndHistory(){try {const auto path=std::filesystem::temp_directory_path()/("pos-stock-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService service(db);pos::ProductDefinition product{"Milk",{}, {}, {}, {},{},"piece",100,150,0,0,10,true,false,{}};const auto id=service.createProduct(product);service.receiveStock({id,20,100,"piece","DUE",QDate::currentDate().addDays(3),"Stock"});auto batch=db->prepare("SELECT id FROM batches WHERE product_id=?");batch.bind(1,id);QVERIFY(batch.stepRow());service.adjustStock({id,batch.text(0),-12,"damaged","Broken seal","Manager"});QCOMPARE(service.lowStock().size(),qsizetype(1));QCOMPARE(service.nearExpiry(QDate::currentDate().addDays(7)).size(),qsizetype(1));QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.adjustStock({id,batch.text(0),-20,"lost","Impossible","Manager"}));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::ean13BarcodeRulesAreEnforced(){pos::BarcodeService service;QCOMPARE(service.generateEan13("590123412345"),QString("5901234123457"));QVERIFY(service.isValidEan13("5901234123457"));QVERIFY(!service.isValidEan13("5901234123458"));QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.generateEan13("ABC"));}
void PosServiceTest::supplierCrudCreatesOpeningLedger(){try{const auto path=std::filesystem::temp_directory_path()/("supplier-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::SupplierService service(db);const auto id=service.create({{},"Acme", "Ali", "0300", "Lahore", 12000, false});auto supplier=service.find(id);QCOMPARE(supplier.name,QString("Acme"));QCOMPARE(supplier.openingBalance,qint64(12000));auto ledger=db->prepare("SELECT balance_paisa FROM supplier_ledger WHERE supplier_id=?");ledger.bind(1,id);QVERIFY(ledger.stepRow());QCOMPARE(ledger.integer(0),qint64(12000));supplier.name="Acme Updated";service.update(supplier);QCOMPARE(service.find(id).name,QString("Acme Updated"));service.archive(id);QVERIFY(service.find(id).archived);}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::purchaseUpdatesStockAndSupplierPayableTogether(){try{const auto path=std::filesystem::temp_directory_path()/("purchase-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService inventory(db);const auto product=inventory.createProduct("Rice","kg",9000,11000,false);pos::SupplierService suppliers(db);const auto supplier=suppliers.create({{},"Wholesale Supplier",{}, {}, {}, 0, false});pos::PurchaseService purchases(db);const auto purchase=purchases.completePurchase({supplier,{},"cash",10000,0,0,{},{{product,10,1000,0,0,"kg",{}, {}}}});QVERIFY(!purchase.purchaseId.isEmpty());auto stock=db->prepare("SELECT stock_quantity FROM products WHERE id=?");stock.bind(1,product);QVERIFY(stock.stepRow());QCOMPARE(stock.integer(0),qint64(10));auto balance=db->prepare("SELECT balance_paisa FROM suppliers WHERE id=?");balance.bind(1,supplier);QVERIFY(balance.stepRow());QCOMPARE(balance.integer(0),qint64(0));auto cash=db->prepare("SELECT SUM(amount_paisa) FROM cash_transactions");QVERIFY(cash.stepRow());QCOMPARE(cash.integer(0),qint64(10000));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::customerPaymentAllocatesToInvoiceAndLedger(){try{const auto path=std::filesystem::temp_directory_path()/("payment-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid(),customer=pos::uuid();insertProduct(*db,product,2);auto insert=db->prepare("INSERT INTO customers(id,name,created_at) VALUES(?,?,?)");insert.bind(1,customer);insert.bind(2,"Paid Customer");insert.bind(3,pos::utcNow());insert.execute();pos::PosService sales(db);const auto sale=sales.completeSale({customer,{},"credit",0,0,{},{{product,{},1,500,0,"piece"}}});pos::PaymentService payments(db);const auto result=payments.recordCustomerPayment(customer,{{sale.saleId,500}},"cash","At counter");QCOMPARE(result.total,qint64(500));auto invoice=db->prepare("SELECT due_paisa,status FROM sales WHERE id=?");invoice.bind(1,sale.saleId);QVERIFY(invoice.stepRow());QCOMPARE(invoice.integer(0),qint64(0));QCOMPARE(invoice.text(1),QString("paid"));auto balance=db->prepare("SELECT balance_paisa FROM customers WHERE id=?");balance.bind(1,customer);QVERIFY(balance.stepRow());QCOMPARE(balance.integer(0),qint64(0));}catch(const std::exception& error){QFAIL(error.what());}}
QTEST_APPLESS_MAIN(PosServiceTest)
#include "pos_service_test.moc"
