#include <QtTest>
#include "core/database.h"
#include "core/pos_service.h"
#include "core/inventory_service.h"
#include "core/barcode_service.h"
#include "core/supplier_service.h"
#include "core/purchase_service.h"
#include "core/payment_service.h"
#include "core/shift_service.h"
#include "core/return_service.h"
#include "core/cheque_service.h"
#include "core/report_service.h"
#include "core/audit_service.h"
#include "core/settings_service.h"
#include "core/excel_export_service.h"
#include "core/security_service.h"
#include "core/suspended_sale_service.h"
#include "core/notification_service.h"
#include "core/backup_service.h"
#include "core/thermal_print_service.h"
#include "core/seed_service.h"
#include "core/commission_service.h"
#include "core/bundle_service.h"
#include "core/partner_service.h"
#include "core/auth_session.h"
#include <filesystem>
#include <QTemporaryDir>
#include <QFile>

class PosServiceTest final : public QObject {
    Q_OBJECT
private slots:
    void saleDecrementsStockAndCreatesLedger();
    void saleRollsBackWhenStockIsInsufficient();
    void receiptCreatesBatchAndMovement();
    void saleConsumesMultipleBatchesByFefo();
    void voidCashSaleReversesCashEntry();
    void catalogAndUnitConversionsAreValidated();
    void stockControlsProduceAlertsAndHistory();
    void ean13BarcodeRulesAreEnforced();
    void supplierCrudCreatesOpeningLedger();
    void purchaseUpdatesStockAndSupplierPayableTogether();
    void purchaseRollsBackWhenLaterLineIsInvalid();
    void customerPaymentAllocatesToInvoiceAndLedger();
    void customerPaymentRollsBackEarlierAllocationsOnFailure();
    void legacySchemaIsUpgradedAndValidated();
    void cashSaleIsAttachedToShiftAndReconciles();
    void salesReturnRestoresStockAndRefundsCash();
    void purchaseReturnReducesStockAndPayable();
    void purchaseReturnRollsBackWhenStockIsInsufficient();
    void chequeRegisterTracksDueAndStatus();
    void reportsAndAuditQueriesReturnPersistedData();
    void settingsPersistAndReadValues();
    void productImportIsAtomicAndValidated();
    void excelExportProducesOpenXmlWorkbook();
    void securityPinStoresOnlySaltedHashAndVerifies();
    void suspendedSaleRoundTripsAndRemoves();
    void mixedSalePersistsTendersAndCashReversal();
    void notificationsCreateReadAndMarkRead();
    void operationalNotificationsAreGenerated();
    void backupRetentionPrunesOldSnapshots();
    void thermalReceiptAndBarcodeBytesAreValidated();
    void demoSeedIsIdempotent();
    void randomSeedCreatesPricedDataIdempotently();
    void commissionSplitIsPersistedPerSaleItem();
    void commissionOverrideRequiredBeyondFlexibleCap();
    void commissionSettingsRejectSharesExceedingRate();
    void bundleResolvesLivePricesAndStock();
    void courseSalePostsOneGroupedEntryUsingCourseSettings();
    void standaloneBookSaleUsesBookSettings();
    void multiCourseAndStandaloneBookSaleReconciles();
    void courseWithNoPartnerSendsFullCommissionToProfit();
    void partnerShareEqualToTotalLeavesNoProfit();
    void partialCourseReturnReversesProportionalShare();
    void fullCancellationReversesAllPartnerAndProfitEntries();
    void changingCommissionSettingsDoesNotAlterPastSales();
    void lockedSessionCannotReadOrChangeCommissionData();
    void wrongOwnerPinIsRejected();
    void cashierCanCompleteCommissionedSaleWhileLocked();
};

// Shared fixture helpers for the partner-commission suite.
static void openShift(pos::Database& db) {
    auto s = db.prepare("INSERT INTO shift_sessions(id,opened_at,opening_cash_paisa,status) VALUES(?,?,?,'open')");
    s.bind(1, pos::uuid()); s.bind(2, pos::utcNow()); s.bind(3, 0); s.execute();
}
static void unlockOwner(const std::shared_ptr<pos::Database>& db) {
    pos::SecurityService(db).setPin("1234");
    pos::AuthSession::instance().setTimeoutSeconds(300);
    QVERIFY(pos::AuthSession::instance().unlock(db, "1234"));
}
static QString stockedBook(pos::InventoryService& inv, const QString& name, qint64 retail) {
    const auto id = inv.createProduct(name, "piece", retail / 2, retail, false);
    inv.receiveStock({id, 50, retail / 2, "piece", {}, {}, "Seed"});
    return id;
}

static void insertProduct(pos::Database& db, const QString& id, qint64 stock) {
    auto p=db.prepare("INSERT INTO products(id,name,base_unit,stock_quantity,created_at,updated_at) VALUES(?,?,?, ?,?,?)");
    p.bind(1,id);p.bind(2,"Test product");p.bind(3,"piece");p.bind(4,stock);p.bind(5,pos::utcNow());p.bind(6,pos::utcNow());p.execute();
    auto shift=db.prepare("INSERT INTO shift_sessions(id,opened_at,opening_cash_paisa,status) VALUES(?,?,?,'open')");shift.bind(1,pos::uuid());shift.bind(2,pos::utcNow());shift.bind(3,0);shift.execute();
}
void PosServiceTest::saleDecrementsStockAndCreatesLedger(){try {const auto path=std::filesystem::temp_directory_path()/("pos-sale-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid(),customer=pos::uuid();insertProduct(*db,product,20);auto c=db->prepare("INSERT INTO customers(id,name,created_at) VALUES(?,?,?)");c.bind(1,customer);c.bind(2,"Customer");c.bind(3,pos::utcNow());c.execute();pos::PosService service(db);pos::SaleRequest request{customer,{},"credit",0,0,{},{{product,{},5,10000,0,"piece"}}};const auto sale=service.completeSale(request);QVERIFY(!sale.saleId.isEmpty());auto p=db->prepare("SELECT stock_quantity FROM products WHERE id=?");p.bind(1,product);QVERIFY(p.stepRow());QCOMPARE(p.integer(0),qint64(15));auto balance=db->prepare("SELECT balance_paisa FROM customers WHERE id=?");balance.bind(1,customer);QVERIFY(balance.stepRow());QCOMPARE(balance.integer(0),qint64(50000));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::saleRollsBackWhenStockIsInsufficient(){try {const auto path=std::filesystem::temp_directory_path()/("pos-rollback-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid();insertProduct(*db,product,2);pos::PosService service(db);pos::SaleRequest request{{},{},"cash",0,0,{},{{product,{},3,100,0,"piece"}}};QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.completeSale(request));auto p=db->prepare("SELECT stock_quantity FROM products WHERE id=?");p.bind(1,product);QVERIFY(p.stepRow());QCOMPARE(p.integer(0),qint64(2));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::receiptCreatesBatchAndMovement(){try {const auto path=std::filesystem::temp_directory_path()/("pos-receipt-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService service(db);const auto product=service.createProduct("Paracetamol","piece",500,800,true);service.receiveStock({product,24,500,"carton","LOT-01",QDate::currentDate().addDays(90),"Receiving"});auto batch=db->prepare("SELECT quantity_remaining FROM batches WHERE product_id=?");batch.bind(1,product);QVERIFY(batch.stepRow());QCOMPARE(batch.integer(0),qint64(24));auto movement=db->prepare("SELECT balance_after FROM stock_movements WHERE product_id=?");movement.bind(1,product);QVERIFY(movement.stepRow());QCOMPARE(movement.integer(0),qint64(24));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::saleConsumesMultipleBatchesByFefo(){try {const auto path=std::filesystem::temp_directory_path()/("pos-fefo-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService inventory(db);const auto product=inventory.createProduct("Vaccine","piece",10,25,true);inventory.receiveStock({product,3,10,"piece","EARLY",QDate::currentDate().addDays(4),"Receiving"});inventory.receiveStock({product,4,10,"piece","LATE",QDate::currentDate().addDays(30),"Receiving"});pos::PosService sales(db);sales.completeSale({{}, {}, "cash", 125, 0, {}, {{product,{},5,25,0,"piece"}}});auto batches=db->prepare("SELECT batch_no,quantity_remaining FROM batches WHERE product_id=? ORDER BY expiry_date");batches.bind(1,product);QVERIFY(batches.stepRow());QCOMPARE(batches.integer(1),qint64(0));QVERIFY(batches.stepRow());QCOMPARE(batches.integer(1),qint64(2));auto items=db->prepare("SELECT COUNT(*) FROM sale_items");QVERIFY(items.stepRow());QCOMPARE(items.integer(0),qint64(2));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::voidCashSaleReversesCashEntry(){try {const auto path=std::filesystem::temp_directory_path()/("pos-void-cash-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid();insertProduct(*db,product,2);pos::PosService service(db);const auto sale=service.completeSale({{}, {}, "cash", 100, 0, {}, {{product,{},1,100,0,"piece"}}});service.voidSale(sale.saleId,"Customer cancelled","Manager");auto cash=db->prepare("SELECT SUM(CASE WHEN type='cash_in' THEN amount_paisa ELSE -amount_paisa END) FROM cash_transactions WHERE sale_id=?");cash.bind(1,sale.saleId);QVERIFY(cash.stepRow());QCOMPARE(cash.integer(0),qint64(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::catalogAndUnitConversionsAreValidated(){try {const auto path=std::filesystem::temp_directory_path()/("pos-catalog-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService service(db);const auto category=service.createCategory("Medicine");const auto brand=service.createBrand("Nexora");QVERIFY(!service.createUnit("Piece","pc").isEmpty());pos::ProductDefinition product{"Syrup","SYR-01","1234567890123",category,brand,{},"piece",100,150,125,110,10,true,false,"C:/images/syrup.png"};const auto productId=service.createProduct(product);service.setUnitConversions(productId,{{"carton",24},{"box",6}});QCOMPARE(service.toBaseQuantity(productId,"carton",2),qint64(48));QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.setUnitConversions(productId,{{"broken",0}}));product.retailPrice=175;service.updateProduct(productId,product);auto updated=db->prepare("SELECT retail_price_paisa,image_path FROM products WHERE id=?");updated.bind(1,productId);QVERIFY(updated.stepRow());QCOMPARE(updated.integer(0),qint64(175));QCOMPARE(updated.text(1),QString("C:/images/syrup.png"));service.archiveProduct(productId);QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.toBaseQuantity(productId,"carton",1));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::stockControlsProduceAlertsAndHistory(){try {const auto path=std::filesystem::temp_directory_path()/("pos-stock-test-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService service(db);pos::ProductDefinition product{"Milk",{}, {}, {}, {},{},"piece",100,150,0,0,10,true,false,{}};const auto id=service.createProduct(product);service.receiveStock({id,20,100,"piece","DUE",QDate::currentDate().addDays(3),"Stock"});auto batch=db->prepare("SELECT id FROM batches WHERE product_id=?");batch.bind(1,id);QVERIFY(batch.stepRow());service.adjustStock({id,batch.text(0),-12,"damaged","Broken seal","Manager"});QCOMPARE(service.lowStock().size(),qsizetype(1));QCOMPARE(service.nearExpiry(QDate::currentDate().addDays(7)).size(),qsizetype(1));QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.adjustStock({id,batch.text(0),-20,"lost","Impossible","Manager"}));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::ean13BarcodeRulesAreEnforced(){pos::BarcodeService service;QCOMPARE(service.generateEan13("590123412345"),QString("5901234123457"));QVERIFY(service.isValidEan13("5901234123457"));QVERIFY(!service.isValidEan13("5901234123458"));QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.generateEan13("ABC"));}
void PosServiceTest::supplierCrudCreatesOpeningLedger(){try{const auto path=std::filesystem::temp_directory_path()/("supplier-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::SupplierService service(db);const auto id=service.create({{},"Acme", "Ali", "0300", "Lahore", 12000, false});auto supplier=service.find(id);QCOMPARE(supplier.name,QString("Acme"));QCOMPARE(supplier.openingBalance,qint64(12000));const auto entries=service.ledger(id);QCOMPARE(entries.size(),qsizetype(1));QCOMPARE(entries.first().debit,qint64(12000));auto ledger=db->prepare("SELECT balance_paisa FROM supplier_ledger WHERE supplier_id=?");ledger.bind(1,id);QVERIFY(ledger.stepRow());QCOMPARE(ledger.integer(0),qint64(12000));supplier.name="Acme Updated";service.update(supplier);QCOMPARE(service.find(id).name,QString("Acme Updated"));service.archive(id);QVERIFY(service.find(id).archived);}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::purchaseUpdatesStockAndSupplierPayableTogether(){try{const auto path=std::filesystem::temp_directory_path()/("purchase-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService inventory(db);const auto product=inventory.createProduct("Rice","kg",9000,11000,false);pos::SupplierService suppliers(db);const auto supplier=suppliers.create({{},"Wholesale Supplier",{}, {}, {}, 0, false});pos::PurchaseService purchases(db);const auto purchase=purchases.completePurchase({supplier,{},"cash",10000,0,0,{},{{product,10,1000,0,0,"kg",{}, {}}}});QVERIFY(!purchase.purchaseId.isEmpty());auto stock=db->prepare("SELECT stock_quantity FROM products WHERE id=?");stock.bind(1,product);QVERIFY(stock.stepRow());QCOMPARE(stock.integer(0),qint64(10));auto balance=db->prepare("SELECT balance_paisa FROM suppliers WHERE id=?");balance.bind(1,supplier);QVERIFY(balance.stepRow());QCOMPARE(balance.integer(0),qint64(0));auto cash=db->prepare("SELECT SUM(amount_paisa) FROM cash_transactions");QVERIFY(cash.stepRow());QCOMPARE(cash.integer(0),qint64(10000));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::customerPaymentAllocatesToInvoiceAndLedger(){try{const auto path=std::filesystem::temp_directory_path()/("payment-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid(),customer=pos::uuid();insertProduct(*db,product,2);auto insert=db->prepare("INSERT INTO customers(id,name,created_at) VALUES(?,?,?)");insert.bind(1,customer);insert.bind(2,"Paid Customer");insert.bind(3,pos::utcNow());insert.execute();pos::PosService sales(db);const auto sale=sales.completeSale({customer,{},"credit",0,0,{},{{product,{},1,500,0,"piece"}}});pos::PaymentService payments(db);const auto result=payments.recordCustomerPayment(customer,{{sale.saleId,500}},"cash","At counter");QCOMPARE(result.total,qint64(500));auto invoice=db->prepare("SELECT due_paisa,status FROM sales WHERE id=?");invoice.bind(1,sale.saleId);QVERIFY(invoice.stepRow());QCOMPARE(invoice.integer(0),qint64(0));QCOMPARE(invoice.text(1),QString("paid"));auto balance=db->prepare("SELECT balance_paisa FROM customers WHERE id=?");balance.bind(1,customer);QVERIFY(balance.stepRow());QCOMPARE(balance.integer(0),qint64(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::legacySchemaIsUpgradedAndValidated(){try{const auto path=std::filesystem::temp_directory_path()/("legacy-schema-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->exec("CREATE TABLE schema_version(version INTEGER NOT NULL); INSERT INTO schema_version VALUES(8); CREATE TABLE customers(id TEXT PRIMARY KEY,name TEXT NOT NULL,created_at TEXT NOT NULL); CREATE TABLE sales(id TEXT PRIMARY KEY,invoice_no TEXT,customer_id TEXT,status TEXT,payment_method TEXT,subtotal_paisa INTEGER,total_paisa INTEGER,created_at TEXT); CREATE TABLE sale_items(id TEXT PRIMARY KEY,sale_id TEXT,product_id TEXT,quantity INTEGER); CREATE TABLE suppliers(id TEXT PRIMARY KEY,name TEXT,created_at TEXT); CREATE TABLE products(id TEXT PRIMARY KEY,name TEXT,base_unit TEXT,created_at TEXT,updated_at TEXT); CREATE TABLE purchases(id TEXT PRIMARY KEY,invoice_no TEXT,supplier_id TEXT,status TEXT,total_paisa INTEGER,purchased_at TEXT); CREATE TABLE cash_transactions(id TEXT PRIMARY KEY,type TEXT,amount_paisa INTEGER,created_at TEXT); CREATE TABLE cheques(id TEXT PRIMARY KEY,direction TEXT,cheque_no TEXT,amount_paisa INTEGER,due_date TEXT,status TEXT,created_at TEXT); CREATE TABLE customer_payments(id TEXT PRIMARY KEY,customer_id TEXT,method TEXT,amount_paisa INTEGER,created_at TEXT); CREATE TABLE customer_ledger(id TEXT PRIMARY KEY,customer_id TEXT,description TEXT,debit_paisa INTEGER,credit_paisa INTEGER,running_balance_paisa INTEGER,created_at TEXT); CREATE TABLE batches(id TEXT PRIMARY KEY,product_id TEXT,batch_no TEXT,quantity_remaining INTEGER,purchase_price_paisa INTEGER,created_at TEXT);");db->migrate();QStringList missing;QVERIFY2(db->isSchemaCompatible(&missing),qPrintable(missing.join(", ")));QVERIFY(missing.isEmpty());}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::cashSaleIsAttachedToShiftAndReconciles(){try{const auto path=std::filesystem::temp_directory_path()/("shift-sale-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid();insertProduct(*db,product,2);pos::PosService sales(db);const auto result=sales.completeSale({{}, {}, "cash", 500, 0, {}, {{product,{},1,500,0,"piece"}}});auto row=db->prepare("SELECT shift_id FROM sales WHERE id=?");row.bind(1,result.saleId);QVERIFY(row.stepRow());QVERIFY(!row.text(0).isEmpty());pos::ShiftService shifts(db);const auto closed=shifts.close(row.text(0),500);QCOMPARE(closed.expected,qint64(500));QCOMPARE(closed.difference,qint64(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::salesReturnRestoresStockAndRefundsCash(){try{const auto path=std::filesystem::temp_directory_path()/("sales-return-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid();insertProduct(*db,product,2);pos::PosService sales(db);const auto sale=sales.completeSale({{}, {}, "cash", 500, 0, {}, {{product,{},1,500,0,"piece"}}});auto item=db->prepare("SELECT id FROM sale_items WHERE sale_id=?");item.bind(1,sale.saleId);QVERIFY(item.stepRow());pos::ReturnService returns(db);const auto result=returns.returnSale(sale.saleId,{{item.text(0),1}},"Damaged",true);QCOMPARE(result.total,qint64(500));auto stock=db->prepare("SELECT stock_quantity FROM products WHERE id=?");stock.bind(1,product);QVERIFY(stock.stepRow());QCOMPARE(stock.integer(0),qint64(2));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::purchaseReturnReducesStockAndPayable(){try{const auto path=std::filesystem::temp_directory_path()/("purchase-return-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService inventory(db);const auto product=inventory.createProduct("Rice","kg",100,150,false);pos::SupplierService suppliers(db);const auto supplier=suppliers.create({{},"Supplier",{},{},{},0,false});pos::PurchaseService purchases(db);const auto purchase=purchases.completePurchase({supplier,{},"credit",0,0,0,{},{{product,5,100,0,0,"kg",{}, {}}}});auto item=db->prepare("SELECT id FROM purchase_items WHERE purchase_id=?");item.bind(1,purchase.purchaseId);QVERIFY(item.stepRow());pos::ReturnService returns(db);returns.returnPurchase(purchase.purchaseId,{{item.text(0),2}},"Overstock");auto stock=db->prepare("SELECT stock_quantity FROM products WHERE id=?");stock.bind(1,product);QVERIFY(stock.stepRow());QCOMPARE(stock.integer(0),qint64(3));auto balance=db->prepare("SELECT balance_paisa FROM suppliers WHERE id=?");balance.bind(1,supplier);QVERIFY(balance.stepRow());QCOMPARE(balance.integer(0),qint64(300));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::chequeRegisterTracksDueAndStatus(){try{const auto path=std::filesystem::temp_directory_path()/("cheque-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::ChequeService cheques(db);const auto id=cheques.record({{},"received",{},"CH-001","HBL",{},25000,QDate::currentDate().addDays(2)});QVERIFY(!id.isEmpty());QCOMPARE(cheques.dueBy(QDate::currentDate().addDays(2)).size(),qsizetype(1));cheques.setStatus(id,"deposited");QCOMPARE(cheques.dueBy(QDate::currentDate().addDays(2)).size(),qsizetype(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::reportsAndAuditQueriesReturnPersistedData(){try{const auto path=std::filesystem::temp_directory_path()/("report-audit-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();auto audit=db->prepare("INSERT INTO audit_log(id,action,entity_type,entity_id,detail,created_at) VALUES(?,?,?,?,?,?)");audit.bind(1,pos::uuid());audit.bind(2,"test_action");audit.bind(3,"test_entity");audit.bind(4,"entity-1");audit.bind(5,"detail");audit.bind(6,pos::utcNow());audit.execute();const auto rows=pos::AuditService(db).recent("test_action");QCOMPARE(rows.size(),qsizetype(1));QCOMPARE(rows.first().entityId,QString("entity-1"));const auto summary=pos::ReportService(db).summary(QDate::currentDate(),QDate::currentDate());QCOMPARE(summary.sales,qint64(0));QCOMPARE(summary.lowStock,qint64(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::settingsPersistAndReadValues(){try{const auto path=std::filesystem::temp_directory_path()/("settings-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::SettingsService settings(db);QCOMPARE(settings.value("business.currency","PKR"),QString("PKR"));settings.setValue("business.name","Nexora Wholesale");QCOMPARE(settings.value("business.name"),QString("Nexora Wholesale"));settings.setValue("business.name","Updated Wholesale");QCOMPARE(settings.value("business.name"),QString("Updated Wholesale"));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::productImportIsAtomicAndValidated(){try{const auto path=std::filesystem::temp_directory_path()/("product-import-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService inventory(db);const QList<pos::ProductDefinition> products={{"Imported A","SKU-A","",{}, {},{},"piece",100,150,0,0,0,false,false,{}},{"Imported B","SKU-B","",{}, {},{},"piece",200,250,0,0,0,false,false,{}}};const auto ids=inventory.importProducts(products);QCOMPARE(ids.size(),qsizetype(2));QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,inventory.importProducts({products.first(),{"Broken",{}, {},{}, {},{},"piece",-1,100,0,0,0,false,false,{}}}));auto count=db->prepare("SELECT COUNT(*) FROM products WHERE is_deleted=0");QVERIFY(count.stepRow());QCOMPARE(count.integer(0),qint64(2));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::excelExportProducesOpenXmlWorkbook(){try{const auto path=QString::fromStdString((std::filesystem::temp_directory_path()/("report-"+pos::uuid().toStdString()+".xlsx")).string());pos::ExcelExportService::writeWorkbook(path,{"Metric","Value"},{{"Sales","100"}});QFile file(path);QVERIFY(file.open(QIODevice::ReadOnly));QCOMPARE(file.read(2),QByteArray("PK"));const auto package=file.readAll();QVERIFY(package.contains("xl/worksheets/sheet1.xml"));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::securityPinStoresOnlySaltedHashAndVerifies(){try{const auto path=std::filesystem::temp_directory_path()/("security-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::SecurityService security(db);QVERIFY(!security.hasPin());QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,security.setPin("12"));security.setPin("1234");QVERIFY(security.hasPin());QVERIFY(security.verifyPin("1234"));QVERIFY(!security.verifyPin("4321"));auto stored=db->prepare("SELECT value FROM settings WHERE key='security.pin_hash'");QVERIFY(stored.stepRow());QVERIFY(!stored.text(0).contains("1234"));security.clearPin();QVERIFY(!security.hasPin());}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::suspendedSaleRoundTripsAndRemoves(){try{const auto path=std::filesystem::temp_directory_path()/("suspended-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::SuspendedSaleService service(db);const auto id=service.save({{"product-1",2,150,"piece"}});QCOMPARE(service.list().size(),qsizetype(1));const auto sale=service.load(id);QCOMPARE(sale.lines.size(),qsizetype(1));QCOMPARE(sale.lines.first().quantity,qint64(2));QCOMPARE(sale.lines.first().unitPrice,qint64(150));service.remove(id);QCOMPARE(service.list().size(),qsizetype(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::mixedSalePersistsTendersAndCashReversal(){try{const auto path=std::filesystem::temp_directory_path()/("mixed-sale-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid();insertProduct(*db,product,5);pos::PosService sales(db);pos::SaleRequest request{{},{},"mixed",0,0,{},{{product,{},1,1000,0,"piece"}}};request.paidAmount=1000;request.tenders={{"cash",400},{"cheque",600}};const auto result=sales.completeSale(request);auto payments=db->prepare("SELECT COUNT(*),SUM(amount_paisa) FROM sale_payments WHERE sale_id=?");payments.bind(1,result.saleId);QVERIFY(payments.stepRow());QCOMPARE(payments.integer(0),qint64(2));QCOMPARE(payments.integer(1),qint64(1000));auto cash=db->prepare("SELECT amount_paisa FROM cash_transactions WHERE sale_id=? AND type='cash_in'");cash.bind(1,result.saleId);QVERIFY(cash.stepRow());QCOMPARE(cash.integer(0),qint64(400));sales.voidSale(result.saleId,"Mixed sale reversal","Manager");auto reversed=db->prepare("SELECT SUM(CASE WHEN type='cash_in' THEN amount_paisa ELSE -amount_paisa END) FROM cash_transactions WHERE sale_id=?");reversed.bind(1,result.saleId);QVERIFY(reversed.stepRow());QCOMPARE(reversed.integer(0),qint64(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::notificationsCreateReadAndMarkRead(){try{const auto path=std::filesystem::temp_directory_path()/("notifications-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::NotificationService service(db);const auto id=service.create("low_stock","Low stock","Rice is below minimum");QCOMPARE(service.unread().size(),qsizetype(1));service.markRead(id);QCOMPARE(service.unread().size(),qsizetype(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::operationalNotificationsAreGenerated(){try{const auto path=std::filesystem::temp_directory_path()/("notification-events-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService inventory(db);pos::ProductDefinition product{"Low stock item",{}, {},{}, {},{},"piece",100,150,0,0,1,false,false,{}};const auto productId=inventory.createProduct(product);inventory.receiveStock({productId,2,100,"piece",{}, {},"Seed"});const auto sale=pos::PosService(db).completeSale({{}, {}, "cash",150,0,{},{{productId,{},1,150,0,"piece"}}});QVERIFY(!sale.saleId.isEmpty());const auto rows=pos::NotificationService(db).unread();bool saleEvent=false,lowStockEvent=false,shiftEvent=false;for(const auto& row:rows){saleEvent|=row.type=="sale";lowStockEvent|=row.type=="low_stock";shiftEvent|=row.type=="shift";}QVERIFY(saleEvent);QVERIFY(lowStockEvent);QVERIFY(shiftEvent);}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::backupRetentionPrunesOldSnapshots(){try{const auto root=std::filesystem::temp_directory_path()/("backup-retention-"+pos::uuid().toStdString());std::filesystem::create_directories(root);const auto live=root/"live.db";auto db=std::make_shared<pos::Database>(live);db->migrate();pos::BackupService service(db);service.createVerifiedBackup(root/"one.db");QTest::qWait(5);service.createVerifiedBackup(root/"two.db");QCOMPARE(service.verifiedBackups().size(),qsizetype(2));service.pruneVerifiedBackups(1);QCOMPARE(service.verifiedBackups().size(),qsizetype(1));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::thermalReceiptAndBarcodeBytesAreValidated(){try{const auto receipt=pos::ThermalPrintService::receiptBytes("Nexora","INV-1",{{"Rice",2,300}},300);QVERIFY(receipt.startsWith(QByteArray("\x1b@")));QVERIFY(receipt.contains("TOTAL (paisa): 300"));QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,pos::ThermalPrintService::receiptBytes("Nexora\x1b","INV-1",{{"Rice",2,300}},300));const auto label=pos::ThermalPrintService::barcodeLabelBytes("Rice","123456789012");QVERIFY(label.contains(QByteArray("\x1dkI")));QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,pos::ThermalPrintService::barcodeLabelBytes("Rice","bad\ncode"));const auto path=QString::fromStdString((std::filesystem::temp_directory_path()/("escpos-"+pos::uuid().toStdString()+".bin")).string());pos::ThermalPrintService::writeRaw(path,label);QFile output(path);QVERIFY(output.open(QIODevice::ReadOnly));QCOMPARE(output.readAll(),label);}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::demoSeedIsIdempotent(){try{const auto path=std::filesystem::temp_directory_path()/("seed-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::SeedService seed(db);seed.seedDemoData();seed.seedDemoData();auto products=db->prepare("SELECT COUNT(*) FROM products WHERE sku LIKE 'DEMO-%'");products.stepRow();QCOMPARE(products.integer(0),qint64(2));auto stock=db->prepare("SELECT SUM(stock_quantity) FROM products WHERE sku LIKE 'DEMO-%'");stock.stepRow();QCOMPARE(stock.integer(0),qint64(37));auto marker=db->prepare("SELECT value FROM settings WHERE key='seed.demo.version'");QVERIFY(marker.stepRow());QCOMPARE(marker.text(0),QString("1"));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::randomSeedCreatesPricedDataIdempotently(){try{const auto path=std::filesystem::temp_directory_path()/("random-seed-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::SeedService seed(db);seed.seedRandomData(8,42);seed.seedRandomData(8,42);auto products=db->prepare("SELECT COUNT(*),MIN(purchase_price_paisa),MAX(retail_price_paisa),SUM(stock_quantity) FROM products WHERE sku LIKE 'RND-42-%'");QVERIFY(products.stepRow());QCOMPARE(products.integer(0),qint64(8));QVERIFY(products.integer(1)>0);QVERIFY(products.integer(2)>products.integer(1));QVERIFY(products.integer(3)>0);}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::purchaseRollsBackWhenLaterLineIsInvalid(){try{const auto path=std::filesystem::temp_directory_path()/("purchase-rollback-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService inventory(db);const auto product=inventory.createProduct("Rice","kg",9000,11000,false);const auto supplier=pos::SupplierService(db).create({{},"Rollback Supplier",{},{},{},0,false});pos::PurchaseRequest request{supplier,{},"credit",0,0,0,{},{{product,2,1000,0,0,"kg",{},{}},{"missing-product",1,1000,0,0,"kg",{}, {}}}};QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,pos::PurchaseService(db).completePurchase(request));auto stock=db->prepare("SELECT stock_quantity FROM products WHERE id=?");stock.bind(1,product);QVERIFY(stock.stepRow());QCOMPARE(stock.integer(0),qint64(0));auto count=db->prepare("SELECT COUNT(*) FROM purchases");QVERIFY(count.stepRow());QCOMPARE(count.integer(0),qint64(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::customerPaymentRollsBackEarlierAllocationsOnFailure(){try{const auto path=std::filesystem::temp_directory_path()/("payment-rollback-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid(),customer=pos::uuid();insertProduct(*db,product,5);auto insert=db->prepare("INSERT INTO customers(id,name,created_at) VALUES(?,?,?)");insert.bind(1,customer);insert.bind(2,"Rollback Customer");insert.bind(3,pos::utcNow());insert.execute();pos::PosService sales(db);const auto first=sales.completeSale({customer,{},"credit",0,0,{},{{product,{},1,500,0,"piece"}}});const auto second=sales.completeSale({customer,{},"credit",0,0,{},{{product,{},1,600,0,"piece"}}});QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,pos::PaymentService(db).recordCustomerPayment(customer,{{first.saleId,500},{second.saleId,601}},"bank","Should rollback"));auto due=db->prepare("SELECT due_paisa FROM sales WHERE id=?");due.bind(1,first.saleId);QVERIFY(due.stepRow());QCOMPARE(due.integer(0),qint64(500));auto count=db->prepare("SELECT COUNT(*) FROM customer_payments");QVERIFY(count.stepRow());QCOMPARE(count.integer(0),qint64(0));auto balance=db->prepare("SELECT balance_paisa FROM customers WHERE id=?");balance.bind(1,customer);QVERIFY(balance.stepRow());QCOMPARE(balance.integer(0),qint64(1100));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::purchaseReturnRollsBackWhenStockIsInsufficient(){try{const auto path=std::filesystem::temp_directory_path()/("purchase-return-rollback-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService inventory(db);const auto product=inventory.createProduct("Rice","kg",100,150,false);const auto supplier=pos::SupplierService(db).create({{},"Supplier",{},{},{},0,false});const auto purchase=pos::PurchaseService(db).completePurchase({supplier,{},"credit",0,0,0,{},{{product,5,100,0,0,"kg",{}, {}}}});auto item=db->prepare("SELECT id FROM purchase_items WHERE purchase_id=?");item.bind(1,purchase.purchaseId);QVERIFY(item.stepRow());inventory.adjustStock({product,{},-4,"lost","Stock unavailable","Manager"});QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,pos::ReturnService(db).returnPurchase(purchase.purchaseId,{{item.text(0),2}},"Overstock"));auto stock=db->prepare("SELECT stock_quantity FROM products WHERE id=?");stock.bind(1,product);QVERIFY(stock.stepRow());QCOMPARE(stock.integer(0),qint64(1));auto returns=db->prepare("SELECT COUNT(*) FROM purchase_returns");QVERIFY(returns.stepRow());QCOMPARE(returns.integer(0),qint64(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::commissionSplitIsPersistedPerSaleItem(){try {const auto path=std::filesystem::temp_directory_path()/("commission-split-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid();insertProduct(*db,product,10);pos::PosService sales(db);pos::SaleRequest request{{},{},"cash",9500,0,{},{{product,{},1,10000,500,"piece"}}};const auto sale=sales.completeSale(request);auto row=db->prepare("SELECT retail_amount_paisa,commission_amount_paisa,partner_amount_paisa,discount_amount_paisa,owner_amount_paisa,overridden FROM sale_item_commissions WHERE sale_id=?");row.bind(1,sale.saleId);QVERIFY(row.stepRow());QCOMPARE(row.integer(0),qint64(10000));QCOMPARE(row.integer(1),qint64(3000));QCOMPARE(row.integer(2),qint64(1000));QCOMPARE(row.integer(3),qint64(500));QCOMPARE(row.integer(4),qint64(1500));QCOMPARE(row.integer(5),qint64(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::commissionOverrideRequiredBeyondFlexibleCap(){try {const auto path=std::filesystem::temp_directory_path()/("commission-override-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();const auto product=pos::uuid();insertProduct(*db,product,10);pos::PosService sales(db);pos::SaleRequest blocked{{},{},"cash",8500,0,{},{{product,{},1,10000,1500,"piece",false}}};QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,sales.completeSale(blocked));auto stock=db->prepare("SELECT stock_quantity FROM products WHERE id=?");stock.bind(1,product);QVERIFY(stock.stepRow());QCOMPARE(stock.integer(0),qint64(10));pos::SaleRequest approved{{},{},"cash",8500,0,{},{{product,{},1,10000,1500,"piece",true}}};const auto sale=sales.completeSale(approved);auto row=db->prepare("SELECT discount_amount_paisa,owner_amount_paisa,overridden FROM sale_item_commissions WHERE sale_id=?");row.bind(1,sale.saleId);QVERIFY(row.stepRow());QCOMPARE(row.integer(0),qint64(1500));QCOMPARE(row.integer(1),qint64(500));QCOMPARE(row.integer(2),qint64(1));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::commissionSettingsRejectSharesExceedingRate(){try {const auto path=std::filesystem::temp_directory_path()/("commission-settings-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::CommissionService service(db);auto settings=service.settings();QCOMPARE(settings.commissionRateBp,qint64(3000));settings.partnerShareBp=2000;settings.ownerMinShareBp=2000;QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,service.setSettings(settings));settings.partnerShareBp=1500;settings.ownerMinShareBp=1000;service.setSettings(settings);QCOMPARE(service.settings().partnerShareBp,qint64(1500));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::bundleResolvesLivePricesAndStock(){try {const auto path=std::filesystem::temp_directory_path()/("bundle-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();pos::InventoryService inventory(db);const auto bookA=inventory.createProduct("Math Grade 5","piece",300,500,false);const auto bookB=inventory.createProduct("English Grade 5","piece",200,400,false);inventory.receiveStock({bookA,10,300,"piece",{}, {},"Seed"});inventory.receiveStock({bookB,10,200,"piece",{}, {},"Seed"});pos::BundleService bundles(db);pos::BundleDefinition definition{"Grade 5 Course","Grade 5","Full set",{{bookA,1},{bookB,1}}};const auto id=bundles.createBundle(definition);QCOMPARE(bundles.listBundles().size(),qsizetype(1));const auto resolved=bundles.resolveItems(id);QCOMPARE(resolved.size(),qsizetype(2));QCOMPARE(resolved.first().retailPrice,qint64(500));QCOMPARE(resolved.first().stock,qint64(10));bundles.archiveBundle(id);QCOMPARE(bundles.listBundles().size(),qsizetype(0));}catch(const std::exception& error){QFAIL(error.what());}}
void PosServiceTest::courseSalePostsOneGroupedEntryUsingCourseSettings(){try{const auto path=std::filesystem::temp_directory_path()/("course-sale-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();unlockOwner(db);openShift(*db);
    pos::InventoryService inv(db);const auto bookA=stockedBook(inv,"Math",1000),bookB=stockedBook(inv,"English",1000);
    pos::PartnerService ps(db);const auto bookPartner=ps.createPartner({{},"Book Partner",{},{},0,false});ps.setBookConfig(bookA,{5000,5000,bookPartner}); // book settings that MUST be ignored inside a course
    const auto course=pos::BundleService(db).createBundle({"Grade 5","G5","",{{bookA,1},{bookB,1}}});
    const auto coursePartner=ps.createPartner({{},"Course Partner",{},{},0,false});ps.setCourseConfig(course,{3000,1000,coursePartner}); // 30% total, 10% partner
    pos::SaleRequest req{{},{},"cash",2000,0,{},{{bookA,{},1,1000,0,"piece",false,course},{bookB,{},1,1000,0,"piece",false,course}}};
    pos::PosService(db).completeSale(req);
    auto courseEntries=db->prepare("SELECT COUNT(*),COALESCE(SUM(commission_paisa),0),COALESCE(SUM(partner_amount_paisa),0),COALESCE(SUM(my_profit_paisa),0) FROM profit_entries WHERE source_type='course'");QVERIFY(courseEntries.stepRow());QCOMPARE(courseEntries.integer(0),qint64(1));QCOMPARE(courseEntries.integer(1),qint64(600));QCOMPARE(courseEntries.integer(2),qint64(200));QCOMPARE(courseEntries.integer(3),qint64(400));
    auto bookEntries=db->prepare("SELECT COUNT(*) FROM profit_entries WHERE source_type='book'");QVERIFY(bookEntries.stepRow());QCOMPARE(bookEntries.integer(0),qint64(0)); // no per-book entries for a course sale
    auto coursePartnerLedger=db->prepare("SELECT COUNT(*),COALESCE(SUM(credit_paisa),0) FROM partner_ledger WHERE partner_id=?");coursePartnerLedger.bind(1,coursePartner);QVERIFY(coursePartnerLedger.stepRow());QCOMPARE(coursePartnerLedger.integer(0),qint64(1));QCOMPARE(coursePartnerLedger.integer(1),qint64(200));
    auto bookPartnerLedger=db->prepare("SELECT COUNT(*) FROM partner_ledger WHERE partner_id=?");bookPartnerLedger.bind(1,bookPartner);QVERIFY(bookPartnerLedger.stepRow());QCOMPARE(bookPartnerLedger.integer(0),qint64(0));
}catch(const std::exception& error){QFAIL(error.what());}}

void PosServiceTest::standaloneBookSaleUsesBookSettings(){try{const auto path=std::filesystem::temp_directory_path()/("book-sale-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();unlockOwner(db);openShift(*db);
    pos::InventoryService inv(db);const auto book=stockedBook(inv,"Atlas",1000);
    pos::PartnerService ps(db);const auto partner=ps.createPartner({{},"Partner",{},{},0,false});ps.setBookConfig(book,{4000,1500,partner}); // 40% total, 15% partner
    pos::SaleRequest req{{},{},"cash",1000,0,{},{{book,{},1,1000,0,"piece"}}}; // no courseId => book settings
    pos::PosService(db).completeSale(req);
    auto entry=db->prepare("SELECT source_type,commission_paisa,partner_amount_paisa,my_profit_paisa FROM profit_entries");QVERIFY(entry.stepRow());QCOMPARE(entry.text(0),QString("book"));QCOMPARE(entry.integer(1),qint64(400));QCOMPARE(entry.integer(2),qint64(150));QCOMPARE(entry.integer(3),qint64(250));
    auto ledger=db->prepare("SELECT credit_paisa FROM partner_ledger WHERE partner_id=?");ledger.bind(1,partner);QVERIFY(ledger.stepRow());QCOMPARE(ledger.integer(0),qint64(150));
}catch(const std::exception& error){QFAIL(error.what());}}

void PosServiceTest::multiCourseAndStandaloneBookSaleReconciles(){try{const auto path=std::filesystem::temp_directory_path()/("multi-sale-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();unlockOwner(db);openShift(*db);
    pos::InventoryService inv(db);const auto a=stockedBook(inv,"A",1000),b=stockedBook(inv,"B",1000),c=stockedBook(inv,"C",1000),loose=stockedBook(inv,"Loose",1000);
    pos::PartnerService ps(db);const auto p1=ps.createPartner({{},"P1",{},{},0,false}),p2=ps.createPartner({{},"P2",{},{},0,false});
    const auto courseA=pos::BundleService(db).createBundle({"CourseA","G1","",{{a,1},{b,1}}});ps.setCourseConfig(courseA,{3000,1000,p1});
    const auto courseB=pos::BundleService(db).createBundle({"CourseB","G2","",{{c,1}}});ps.setCourseConfig(courseB,{2000,2000,p2});
    ps.setBookConfig(loose,{5000,1000,p1});
    pos::SaleRequest req{{},{},"cash",4000,0,{},{{a,{},1,1000,0,"piece",false,courseA},{b,{},1,1000,0,"piece",false,courseA},{c,{},1,1000,0,"piece",false,courseB},{loose,{},1,1000,0,"piece"}}};
    pos::PosService(db).completeSale(req);
    const auto today=QDate::currentDate();const auto sum=ps.summary(today,today);
    // courseA: value2000 comm600 partner200 profit400; courseB: value1000 comm200 partner200 profit0; loose: value1000 comm500 partner100 profit400
    QCOMPARE(sum.totalCommission,qint64(1300));QCOMPARE(sum.totalPartner,qint64(500));QCOMPARE(sum.myProfit,qint64(800));
    QCOMPARE(sum.totalPartner+sum.myProfit,sum.totalCommission);
    qint64 courseSum=0;for(const auto& r:ps.courseReport(today,today))courseSum+=r.commission;qint64 bookSum=0;for(const auto& r:ps.standaloneBookReport(today,today))bookSum+=r.commission;
    QCOMPARE(courseSum+bookSum,sum.totalCommission); // per-source rows reconcile to the summary
    QCOMPARE(sum.totalOwed,qint64(500));
}catch(const std::exception& error){QFAIL(error.what());}}

void PosServiceTest::courseWithNoPartnerSendsFullCommissionToProfit(){try{const auto path=std::filesystem::temp_directory_path()/("nopartner-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();unlockOwner(db);openShift(*db);
    pos::InventoryService inv(db);const auto book=stockedBook(inv,"Solo",1000);
    pos::PartnerService ps(db);const auto course=pos::BundleService(db).createBundle({"NoPartner","G","",{{book,1}}});ps.setCourseConfig(course,{3000,0,{}}); // 30% total, no partner
    pos::SaleRequest req{{},{},"cash",1000,0,{},{{book,{},1,1000,0,"piece",false,course}}};pos::PosService(db).completeSale(req);
    auto entry=db->prepare("SELECT commission_paisa,partner_amount_paisa,my_profit_paisa FROM profit_entries");QVERIFY(entry.stepRow());QCOMPARE(entry.integer(0),qint64(300));QCOMPARE(entry.integer(1),qint64(0));QCOMPARE(entry.integer(2),qint64(300));
    auto ledger=db->prepare("SELECT COUNT(*) FROM partner_ledger");QVERIFY(ledger.stepRow());QCOMPARE(ledger.integer(0),qint64(0));
}catch(const std::exception& error){QFAIL(error.what());}}

void PosServiceTest::partnerShareEqualToTotalLeavesNoProfit(){try{const auto path=std::filesystem::temp_directory_path()/("equalshare-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();unlockOwner(db);openShift(*db);
    pos::InventoryService inv(db);const auto book=stockedBook(inv,"Equal",1000);
    pos::PartnerService ps(db);const auto partner=ps.createPartner({{},"Full Partner",{},{},0,false});const auto course=pos::BundleService(db).createBundle({"Equal","G","",{{book,1}}});ps.setCourseConfig(course,{4000,4000,partner});
    pos::SaleRequest req{{},{},"cash",1000,0,{},{{book,{},1,1000,0,"piece",false,course}}};pos::PosService(db).completeSale(req);
    auto entry=db->prepare("SELECT commission_paisa,partner_amount_paisa,my_profit_paisa FROM profit_entries");QVERIFY(entry.stepRow());QCOMPARE(entry.integer(0),qint64(400));QCOMPARE(entry.integer(1),qint64(400));QCOMPARE(entry.integer(2),qint64(0));
}catch(const std::exception& error){QFAIL(error.what());}}

void PosServiceTest::partialCourseReturnReversesProportionalShare(){try{const auto path=std::filesystem::temp_directory_path()/("partial-return-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();unlockOwner(db);openShift(*db);
    pos::InventoryService inv(db);const auto bookA=stockedBook(inv,"Math",1000),bookB=stockedBook(inv,"English",1000);
    pos::PartnerService ps(db);const auto partner=ps.createPartner({{},"Partner",{},{},0,false});const auto course=pos::BundleService(db).createBundle({"Grade 5","G5","",{{bookA,1},{bookB,1}}});ps.setCourseConfig(course,{3000,1000,partner});
    pos::SaleRequest req{{},{},"cash",2000,0,{},{{bookA,{},1,1000,0,"piece",false,course},{bookB,{},1,1000,0,"piece",false,course}}};const auto sale=pos::PosService(db).completeSale(req);
    auto itemB=db->prepare("SELECT id FROM sale_items WHERE sale_id=? AND product_id=?");itemB.bind(1,sale.saleId);itemB.bind(2,bookB);QVERIFY(itemB.stepRow());
    pos::ReturnService(db).returnSale(sale.saleId,{{itemB.text(0),1}},"Damaged",true);
    auto net=db->prepare("SELECT COALESCE(SUM(commission_paisa),0),COALESCE(SUM(partner_amount_paisa),0),COALESCE(SUM(my_profit_paisa),0) FROM profit_entries WHERE source_type='course'");QVERIFY(net.stepRow());QCOMPARE(net.integer(0),qint64(300));QCOMPARE(net.integer(1),qint64(100));QCOMPARE(net.integer(2),qint64(200)); // half reversed
    auto balance=db->prepare("SELECT balance_paisa FROM partners WHERE id=?");balance.bind(1,partner);QVERIFY(balance.stepRow());QCOMPARE(balance.integer(0),qint64(100));
}catch(const std::exception& error){QFAIL(error.what());}}

void PosServiceTest::fullCancellationReversesAllPartnerAndProfitEntries(){try{const auto path=std::filesystem::temp_directory_path()/("full-cancel-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();unlockOwner(db);openShift(*db);
    pos::InventoryService inv(db);const auto bookA=stockedBook(inv,"Math",1000),bookB=stockedBook(inv,"English",1000);
    pos::PartnerService ps(db);const auto partner=ps.createPartner({{},"Partner",{},{},0,false});const auto course=pos::BundleService(db).createBundle({"Grade 5","G5","",{{bookA,1},{bookB,1}}});ps.setCourseConfig(course,{3000,1000,partner});
    pos::SaleRequest req{{},{},"cash",2000,0,{},{{bookA,{},1,1000,0,"piece",false,course},{bookB,{},1,1000,0,"piece",false,course}}};const auto sale=pos::PosService(db).completeSale(req);
    pos::PosService(db).voidSale(sale.saleId,"Customer cancelled","Manager");
    auto net=db->prepare("SELECT COALESCE(SUM(commission_paisa),0),COALESCE(SUM(partner_amount_paisa),0),COALESCE(SUM(my_profit_paisa),0) FROM profit_entries WHERE sale_id=?");net.bind(1,sale.saleId);QVERIFY(net.stepRow());QCOMPARE(net.integer(0),qint64(0));QCOMPARE(net.integer(1),qint64(0));QCOMPARE(net.integer(2),qint64(0));
    auto balance=db->prepare("SELECT balance_paisa FROM partners WHERE id=?");balance.bind(1,partner);QVERIFY(balance.stepRow());QCOMPARE(balance.integer(0),qint64(0));
    auto history=db->prepare("SELECT COUNT(*) FROM profit_entries WHERE sale_id=?");history.bind(1,sale.saleId);QVERIFY(history.stepRow());QVERIFY(history.integer(0)>=2); // original + reversal kept, not deleted
}catch(const std::exception& error){QFAIL(error.what());}}

void PosServiceTest::changingCommissionSettingsDoesNotAlterPastSales(){try{const auto path=std::filesystem::temp_directory_path()/("frozen-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();unlockOwner(db);openShift(*db);
    pos::InventoryService inv(db);const auto book=stockedBook(inv,"Math",1000);
    pos::PartnerService ps(db);const auto partner=ps.createPartner({{},"Partner",{},{},0,false});const auto course=pos::BundleService(db).createBundle({"Grade 5","G5","",{{book,1}}});ps.setCourseConfig(course,{3000,1000,partner});
    pos::SaleRequest req{{},{},"cash",1000,0,{},{{book,{},1,1000,0,"piece",false,course}}};pos::PosService(db).completeSale(req);
    ps.setCourseConfig(course,{5000,5000,partner}); // change AFTER the sale
    auto entry=db->prepare("SELECT commission_paisa,partner_amount_paisa,my_profit_paisa FROM profit_entries");QVERIFY(entry.stepRow());QCOMPARE(entry.integer(0),qint64(300));QCOMPARE(entry.integer(1),qint64(100));QCOMPARE(entry.integer(2),qint64(200)); // still the old snapshot
    const auto today=QDate::currentDate();bool found=false;for(const auto& r:ps.courseReport(today,today)){if(r.sourceId==course){found=true;QCOMPARE(r.commission,qint64(300));QCOMPARE(r.partnerAmount,qint64(100));}}QVERIFY(found);
}catch(const std::exception& error){QFAIL(error.what());}}

void PosServiceTest::lockedSessionCannotReadOrChangeCommissionData(){try{const auto path=std::filesystem::temp_directory_path()/("locked-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();unlockOwner(db);
    pos::PartnerService ps(db);const auto partner=ps.createPartner({{},"Partner",{},{},0,false});const auto book=pos::InventoryService(db).createProduct("Book","piece",500,1000,false);
    pos::AuthSession::instance().lock(); // simulate a cashier / logged-out session
    const auto today=QDate::currentDate();
    QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,ps.listPartners());
    QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,ps.summary(today,today));
    QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,ps.partnerLedger(partner,today,today));
    QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,ps.setBookConfig(book,{3000,1000,partner}));
    QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,ps.recordPayout(partner,100,"nope"));
}catch(const std::exception& error){QFAIL(error.what());}}

void PosServiceTest::wrongOwnerPinIsRejected(){try{const auto path=std::filesystem::temp_directory_path()/("wrongpin-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();
    pos::SecurityService(db).setPin("1234");pos::AuthSession::instance().lock();
    QVERIFY(!pos::AuthSession::instance().unlock(db,"0000"));
    QVERIFY(!pos::AuthSession::instance().isUnlocked());
    QVERIFY_THROWS_EXCEPTION(pos::DatabaseError,pos::PartnerService(db).listPartners());
    QVERIFY(pos::AuthSession::instance().unlock(db,"1234"));
    QVERIFY(pos::AuthSession::instance().isUnlocked());
}catch(const std::exception& error){QFAIL(error.what());}}

void PosServiceTest::cashierCanCompleteCommissionedSaleWhileLocked(){try{const auto path=std::filesystem::temp_directory_path()/("cashier-locked-"+pos::uuid().toStdString()+".db");auto db=std::make_shared<pos::Database>(path);db->migrate();unlockOwner(db);openShift(*db);
    pos::InventoryService inv(db);const auto book=stockedBook(inv,"Math",1000);
    pos::PartnerService ps(db);const auto partner=ps.createPartner({{},"Partner",{},{},0,false});const auto course=pos::BundleService(db).createBundle({"Grade 5","G5","",{{book,1}}});ps.setCourseConfig(course,{3000,1000,partner});
    pos::AuthSession::instance().lock(); // cashier / logged-out — must still record commission in the background
    pos::SaleRequest req{{},{},"cash",1000,0,{},{{book,{},1,1000,0,"piece",false,course}}};pos::PosService(db).completeSale(req); // must not throw for a cashier
    auto entry=db->prepare("SELECT commission_paisa,partner_amount_paisa FROM profit_entries");QVERIFY(entry.stepRow());QCOMPARE(entry.integer(0),qint64(300));QCOMPARE(entry.integer(1),qint64(100));
    QVERIFY(pos::AuthSession::instance().unlock(db,"1234"));
    const auto today=QDate::currentDate();bool found=false;for(const auto& r:ps.partnerReport(today,today)){if(r.partnerId==partner){found=true;QCOMPARE(r.earned,qint64(100));QCOMPARE(r.balance,qint64(100));}}QVERIFY(found);
}catch(const std::exception& error){QFAIL(error.what());}}

QTEST_APPLESS_MAIN(PosServiceTest)
#include "pos_service_test.moc"
