# CMake generated Testfile for 
# Source directory: E:/pos--2
# Build directory: E:/pos--2/build-logo
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[pos_core_tests]=] "E:/pos--2/build-logo/pos_core_tests.exe")
set_tests_properties([=[pos_core_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/pos--2/CMakeLists.txt;88;add_test;E:/pos--2/CMakeLists.txt;0;")
add_test([=[pos_ui_smoke_tests]=] "E:/pos--2/build-logo/pos_ui_smoke_tests.exe")
set_tests_properties([=[pos_ui_smoke_tests]=] PROPERTIES  ENVIRONMENT "PATH=C:/Qt/6.11.1/mingw_64/bin;c:\\Users\\ADMIN\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand;c:\\Users\\ADMIN\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\copilotCli;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\MinGW\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\ADMIN\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages;C:\\Users\\ADMIN\\AppData\\Local\\Python\\pythoncore-3.14-64\\Scripts;C:\\Program Files\\Java\\jdk-25.0.3\\bin;C:\\Program Files\\Redis\\;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Program Files\\nodejs\\;C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\;C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python312\\;C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Launcher\\;C:\\Users\\ADMIN\\.grok\\bin;C:\\Users\\ADMIN\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\ADMIN\\AppData\\Local\\Python\\bin;C:\\Users\\ADMIN\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages;C:\\Users\\ADMIN\\AppData\\Local\\Python\\pythoncore-3.14-64\\Scripts;C:\\intelFPGA\\20.1\\modelsim_ase\\win32aloem;C:\\maven\\apache-maven-3.9.6\\bin;C:\\Users\\ADMIN\\AppData\\Local\\Programs\\cursor\\resources\\app\\bin;E:\\trashFiles\\IntelliJ IDEA 2026.1.3\\bin;C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Antigravity IDE\\bin;C:\\Users\\ADMIN\\AppData\\Local\\Programs\\Ollama;C:\\Users\\ADMIN\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Anthropic.ClaudeCode_Microsoft.Winget.Source_8wekyb3d8bbwe;C:\\Users\\ADMIN\\AppData\\Roaming\\npm" _BACKTRACE_TRIPLES "E:/pos--2/CMakeLists.txt;91;add_test;E:/pos--2/CMakeLists.txt;0;")
