#include "core/excel_export_service.h"
#include "core/database.h"
#include <QFile>

namespace pos {
namespace {
QString xmlEscape(const QString& value){QString escaped=value;escaped.replace('&',"&amp;");escaped.replace('<',"&lt;");escaped.replace('>',"&gt;");escaped.replace('"',"&quot;");escaped.replace('\'',"&apos;");return escaped;}
void put16(QByteArray& output, quint16 value){output.append(char(value&0xff));output.append(char((value>>8)&0xff));}
void put32(QByteArray& output, quint32 value){for(int i=0;i<4;++i)output.append(char((value>>(8*i))&0xff));}
quint32 crc32(const QByteArray& data){quint32 crc=0xffffffffu;for(const auto byte: data){crc^=static_cast<unsigned char>(byte);for(int i=0;i<8;++i)crc=(crc>>1)^((crc&1)?0xedb88320u:0u);}return crc^0xffffffffu;}
QByteArray worksheet(const QStringList& headers,const QList<QStringList>& rows){QByteArray xml("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetData>");int rowNumber=1;auto appendRow=[&xml,rowNumber](const QStringList& values) mutable {xml.append("<row r=\""+QByteArray::number(rowNumber)+"\">");for(int column=0;column<values.size();++column){const auto cell=xmlEscape(values.at(column)).toUtf8();xml.append("<c r=\"");xml.append(QByteArray(1,char('A'+(column%26))));xml.append(QByteArray::number(rowNumber));xml.append("\" t=\"inlineStr\"><is><t xml:space=\"preserve\">");xml.append(cell);xml.append("</t></is></c>");}xml.append("</row>");++rowNumber;};appendRow(headers);for(const auto& row:rows)appendRow(row);xml.append("</sheetData></worksheet>");return xml;}
void addZipFile(QFile& file,const QByteArray& name,const QByteArray& data,QByteArray& central){const auto offset=static_cast<quint32>(file.pos());const auto crc=crc32(data);QByteArray local;put32(local,0x04034b50u);put16(local,20);put16(local,0);put16(local,0);put16(local,0);put16(local,0);put32(local,crc);put32(local,static_cast<quint32>(data.size()));put32(local,static_cast<quint32>(data.size()));put16(local,static_cast<quint16>(name.size()));put16(local,0);local.append(name);file.write(local);file.write(data);put32(central,0x02014b50u);put16(central,20);put16(central,20);put16(central,0);put16(central,0);put16(central,0);put16(central,0);put32(central,crc);put32(central,static_cast<quint32>(data.size()));put32(central,static_cast<quint32>(data.size()));put16(central,static_cast<quint16>(name.size()));put16(central,0);put16(central,0);put16(central,0);put16(central,0);put32(central,0);put32(central,offset);central.append(name);}
}
void ExcelExportService::writeWorkbook(const QString& fileName,const QStringList& headers,const QList<QStringList>& rows){if(fileName.trimmed().isEmpty()||headers.isEmpty())throw DatabaseError("invalid Excel export request");for(const auto& row:rows)if(row.size()!=headers.size())throw DatabaseError("Excel export row width does not match headers");QFile file(fileName);if(!file.open(QIODevice::WriteOnly|QIODevice::Truncate))throw DatabaseError("could not open Excel export file");const QByteArray types("<?xml version=\"1.0\" encoding=\"UTF-8\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>");const QByteArray rootRels("<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");const QByteArray workbook("<?xml version=\"1.0\" encoding=\"UTF-8\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Summary\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>");const QByteArray workbookRels("<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/></Relationships>");const auto sheet=worksheet(headers,rows);QByteArray central;addZipFile(file,"[Content_Types].xml",types,central);addZipFile(file,"_rels/.rels",rootRels,central);addZipFile(file,"xl/workbook.xml",workbook,central);addZipFile(file,"xl/_rels/workbook.xml.rels",workbookRels,central);addZipFile(file,"xl/worksheets/sheet1.xml",sheet,central);const auto centralOffset=static_cast<quint32>(file.pos());file.write(central);QByteArray end;put32(end,0x06054b50u);put16(end,0);put16(end,0);put16(end,5);put16(end,5);put32(end,static_cast<quint32>(central.size()));put32(end,centralOffset);put16(end,0);file.write(end);file.close();}
}
