#include "core/inventory_service.h"
#include "core/database.h"
#include <limits>

namespace pos {
InventoryService::InventoryService(std::shared_ptr<Database> database) : db_(std::move(database)) {}
QString InventoryService::createProduct(const QString& name, const QString& baseUnit, Money purchasePrice, Money retailPrice, bool trackBatches) {
    return createProduct({name, {}, {}, {}, {}, {}, baseUnit, purchasePrice, retailPrice, 0, 0, 0, trackBatches, false, {}});
}
QString InventoryService::createProduct(const ProductDefinition& product) {
    if(product.name.trimmed().isEmpty() || product.baseUnit.trimmed().isEmpty() || product.purchasePrice<0 || product.retailPrice<0 || product.wholesalePrice<0 || product.dealerPrice<0 || product.minimumStock<0) throw DatabaseError("invalid product data");
    Transaction tx(db_->handle()); const auto id=uuid(); auto insert=db_->prepare("INSERT INTO products(id,name,sku,barcode,category_id,brand_id,description,base_unit,track_batches,track_expiry,purchase_price_paisa,retail_price_paisa,wholesale_price_paisa,dealer_price_paisa,minimum_stock,image_path,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    insert.bind(1,id);insert.bind(2,product.name.trimmed());if(product.sku.isEmpty())insert.bindNull(3);else insert.bind(3,product.sku);if(product.barcode.isEmpty())insert.bindNull(4);else insert.bind(4,product.barcode);if(product.categoryId.isEmpty())insert.bindNull(5);else insert.bind(5,product.categoryId);if(product.brandId.isEmpty())insert.bindNull(6);else insert.bind(6,product.brandId);insert.bind(7,product.description.trimmed());insert.bind(8,product.baseUnit.trimmed());insert.bind(9,product.trackBatches?1:0);insert.bind(10,product.trackExpiry?1:0);insert.bind(11,product.purchasePrice);insert.bind(12,product.retailPrice);insert.bind(13,product.wholesalePrice);insert.bind(14,product.dealerPrice);insert.bind(15,product.minimumStock);if(product.imagePath.isEmpty())insert.bindNull(16);else insert.bind(16,product.imagePath);insert.bind(17,utcNow());insert.bind(18,utcNow());insert.execute();tx.commit();return id;
}
void InventoryService::updateProduct(const QString& id,const ProductDefinition& product){if(product.name.trimmed().isEmpty()||product.baseUnit.trimmed().isEmpty()||product.purchasePrice<0||product.retailPrice<0||product.wholesalePrice<0||product.dealerPrice<0||product.minimumStock<0)throw DatabaseError("invalid product data");Transaction tx(db_->handle());auto update=db_->prepare("UPDATE products SET name=?,sku=?,barcode=?,category_id=?,brand_id=?,description=?,base_unit=?,track_batches=?,track_expiry=?,purchase_price_paisa=?,retail_price_paisa=?,wholesale_price_paisa=?,dealer_price_paisa=?,minimum_stock=?,image_path=?,updated_at=? WHERE id=? AND is_deleted=0");update.bind(1,product.name.trimmed());if(product.sku.isEmpty())update.bindNull(2);else update.bind(2,product.sku);if(product.barcode.isEmpty())update.bindNull(3);else update.bind(3,product.barcode);if(product.categoryId.isEmpty())update.bindNull(4);else update.bind(4,product.categoryId);if(product.brandId.isEmpty())update.bindNull(5);else update.bind(5,product.brandId);update.bind(6,product.description.trimmed());update.bind(7,product.baseUnit);update.bind(8,product.trackBatches?1:0);update.bind(9,product.trackExpiry?1:0);update.bind(10,product.purchasePrice);update.bind(11,product.retailPrice);update.bind(12,product.wholesalePrice);update.bind(13,product.dealerPrice);update.bind(14,product.minimumStock);if(product.imagePath.isEmpty())update.bindNull(15);else update.bind(15,product.imagePath);update.bind(16,utcNow());update.bind(17,id);update.execute();if(sqlite3_changes(db_->handle())!=1)throw DatabaseError("product not found");tx.commit();}
void InventoryService::archiveProduct(const QString& id){Transaction tx(db_->handle());auto update=db_->prepare("UPDATE products SET is_deleted=1,updated_at=? WHERE id=? AND is_deleted=0");update.bind(1,utcNow());update.bind(2,id);update.execute();if(sqlite3_changes(db_->handle())!=1)throw DatabaseError("product not found");tx.commit();}
QString InventoryService::cloneProduct(const QString& id,const QString& name,const QString& sku,const QString& barcode){auto source=db_->prepare("SELECT category_id,brand_id,description,base_unit,purchase_price_paisa,retail_price_paisa,wholesale_price_paisa,dealer_price_paisa,minimum_stock,track_batches,track_expiry,image_path FROM products WHERE id=? AND is_deleted=0");source.bind(1,id);if(!source.stepRow())throw DatabaseError("product not found");return createProduct({name,sku,barcode,source.text(0),source.text(1),source.text(2),source.text(3),source.integer(4),source.integer(5),source.integer(6),source.integer(7),source.integer(8),source.integer(9)!=0,source.integer(10)!=0,source.text(11)});}
QString InventoryService::createCategory(const QString& name){if(name.trimmed().isEmpty())throw DatabaseError("category name is required");Transaction tx(db_->handle());const auto id=uuid();auto insert=db_->prepare("INSERT INTO categories(id,name,created_at) VALUES(?,?,?)");insert.bind(1,id);insert.bind(2,name.trimmed());insert.bind(3,utcNow());insert.execute();tx.commit();return id;}
QString InventoryService::createBrand(const QString& name){if(name.trimmed().isEmpty())throw DatabaseError("brand name is required");Transaction tx(db_->handle());const auto id=uuid();auto insert=db_->prepare("INSERT INTO brands(id,name,created_at) VALUES(?,?,?)");insert.bind(1,id);insert.bind(2,name.trimmed());insert.bind(3,utcNow());insert.execute();tx.commit();return id;}
QString InventoryService::createUnit(const QString& name,const QString& symbol){if(name.trimmed().isEmpty()||symbol.trimmed().isEmpty())throw DatabaseError("unit name and symbol are required");Transaction tx(db_->handle());const auto id=uuid();auto insert=db_->prepare("INSERT INTO units(id,name,symbol,created_at) VALUES(?,?,?,?)");insert.bind(1,id);insert.bind(2,name.trimmed());insert.bind(3,symbol.trimmed());insert.bind(4,utcNow());insert.execute();tx.commit();return id;}
void InventoryService::archiveCategory(const QString& id){Transaction tx(db_->handle());auto update=db_->prepare("UPDATE categories SET deleted_at=? WHERE id=? AND deleted_at IS NULL");update.bind(1,utcNow());update.bind(2,id);update.execute();if(sqlite3_changes(db_->handle())!=1)throw DatabaseError("category not found");tx.commit();}
void InventoryService::archiveBrand(const QString& id){Transaction tx(db_->handle());auto update=db_->prepare("UPDATE brands SET deleted_at=? WHERE id=? AND deleted_at IS NULL");update.bind(1,utcNow());update.bind(2,id);update.execute();if(sqlite3_changes(db_->handle())!=1)throw DatabaseError("brand not found");tx.commit();}
void InventoryService::setUnitConversions(const QString& productId,const QList<UnitConversion>& conversions){Transaction tx(db_->handle());auto exists=db_->prepare("SELECT id FROM products WHERE id=? AND is_deleted=0");exists.bind(1,productId);if(!exists.stepRow())throw DatabaseError("product not found");for(const auto& conversion:conversions){if(conversion.name.trimmed().isEmpty()||conversion.factor<=0)throw DatabaseError("invalid unit conversion");}auto clear=db_->prepare("DELETE FROM product_units WHERE product_id=?");clear.bind(1,productId);clear.execute();for(const auto& conversion:conversions){auto insert=db_->prepare("INSERT INTO product_units(id,product_id,name,factor) VALUES(?,?,?,?)");insert.bind(1,uuid());insert.bind(2,productId);insert.bind(3,conversion.name.trimmed());insert.bind(4,conversion.factor);insert.execute();}tx.commit();}
Quantity InventoryService::toBaseQuantity(const QString& productId,const QString& unitName,Quantity quantity) const {if(quantity<=0)throw DatabaseError("quantity must be positive");auto product=db_->prepare("SELECT base_unit FROM products WHERE id=? AND is_deleted=0");product.bind(1,productId);if(!product.stepRow())throw DatabaseError("product not found");if(product.text(0).compare(unitName,Qt::CaseInsensitive)==0)return quantity;auto unit=db_->prepare("SELECT factor FROM product_units WHERE product_id=? AND name=?");unit.bind(1,productId);unit.bind(2,unitName);if(!unit.stepRow())throw DatabaseError("product unit not found");if(quantity>std::numeric_limits<Quantity>::max()/unit.integer(0))throw DatabaseError("quantity conversion overflow");return quantity*unit.integer(0);}
void InventoryService::adjustStock(const StockAdjustment& adjustment){if(adjustment.quantityDelta==0||adjustment.reason.trimmed().isEmpty()||(adjustment.type!="manual_adjustment"&&adjustment.type!="damaged"&&adjustment.type!="lost"&&adjustment.type!="expiry_writeoff"))throw DatabaseError("invalid stock adjustment");Transaction tx(db_->handle());auto product=db_->prepare("SELECT stock_quantity,track_batches FROM products WHERE id=? AND is_deleted=0");product.bind(1,adjustment.productId);if(!product.stepRow())throw DatabaseError("product not found");const auto before=product.integer(0);const auto tracks=product.integer(1)!=0;if(before+adjustment.quantityDelta<0)throw DatabaseError("stock cannot become negative");if(tracks&&adjustment.batchId.isEmpty())throw DatabaseError("batch is required for tracked product");if(!adjustment.batchId.isEmpty()){auto batch=db_->prepare("UPDATE batches SET quantity_remaining=quantity_remaining+? WHERE id=? AND product_id=? AND quantity_remaining+?>=0");batch.bind(1,adjustment.quantityDelta);batch.bind(2,adjustment.batchId);batch.bind(3,adjustment.productId);batch.bind(4,adjustment.quantityDelta);batch.execute();if(sqlite3_changes(db_->handle())!=1)throw DatabaseError("batch stock cannot become negative");}auto update=db_->prepare("UPDATE products SET stock_quantity=stock_quantity+?,updated_at=? WHERE id=?");update.bind(1,adjustment.quantityDelta);update.bind(2,utcNow());update.bind(3,adjustment.productId);update.execute();auto move=db_->prepare("INSERT INTO stock_movements(id,product_id,batch_id,type,quantity,reason,balance_after,performed_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)");move.bind(1,uuid());move.bind(2,adjustment.productId);if(adjustment.batchId.isEmpty())move.bindNull(3);else move.bind(3,adjustment.batchId);move.bind(4,adjustment.type);move.bind(5,adjustment.quantityDelta);move.bind(6,adjustment.reason.trimmed());move.bind(7,before+adjustment.quantityDelta);move.bind(8,adjustment.performedBy);move.bind(9,utcNow());move.execute();tx.commit();}
QList<InventoryAlert> InventoryService::lowStock() const {QList<InventoryAlert> result;auto query=db_->prepare("SELECT id,name,stock_quantity FROM products WHERE is_deleted=0 AND stock_quantity<=minimum_stock ORDER BY stock_quantity,name");while(query.stepRow())result.append({query.text(0),query.text(1),query.integer(2),{}, {}});return result;}
QList<InventoryAlert> InventoryService::nearExpiry(const QDate& until) const {if(!until.isValid())throw DatabaseError("expiry cutoff is required");QList<InventoryAlert> result;auto query=db_->prepare("SELECT p.id,p.name,b.quantity_remaining,b.id,b.expiry_date FROM batches b JOIN products p ON p.id=b.product_id WHERE p.is_deleted=0 AND b.quantity_remaining>0 AND b.expiry_date IS NOT NULL AND b.expiry_date<=? ORDER BY b.expiry_date,p.name");query.bind(1,until.toString(Qt::ISODate));while(query.stepRow())result.append({query.text(0),query.text(1),query.integer(2),query.text(3),QDate::fromString(query.text(4),Qt::ISODate)});return result;}
void InventoryService::receiveStock(const StockReceipt& receipt) {
    if (receipt.quantity <= 0 || receipt.purchasePrice < 0) {
        throw DatabaseError("invalid stock receipt");
    }
    Transaction tx(db_->handle());
    auto product=db_->prepare("SELECT stock_quantity,track_batches FROM products WHERE id=? AND is_deleted=0");product.bind(1,receipt.productId);if(!product.stepRow())throw DatabaseError("product not found");const auto previous=product.integer(0);const bool tracks=product.integer(1)!=0;QString batchId;
    if(tracks){if(receipt.batchNo.trimmed().isEmpty())throw DatabaseError("batch number is required");batchId=uuid();auto batch=db_->prepare("INSERT INTO batches(id,product_id,batch_no,expiry_date,quantity_remaining,purchase_price_paisa,created_at) VALUES(?,?,?,?,?,?,?)");batch.bind(1,batchId);batch.bind(2,receipt.productId);batch.bind(3,receipt.batchNo.trimmed());if(receipt.expiryDate.isValid())batch.bind(4,receipt.expiryDate.toString(Qt::ISODate));else batch.bindNull(4);batch.bind(5,receipt.quantity);batch.bind(6,receipt.purchasePrice);batch.bind(7,utcNow());batch.execute();}
    auto update=db_->prepare("UPDATE products SET stock_quantity=stock_quantity+?,purchase_price_paisa=?,updated_at=? WHERE id=?");update.bind(1,receipt.quantity);update.bind(2,receipt.purchasePrice);update.bind(3,utcNow());update.bind(4,receipt.productId);update.execute();
    auto movement=db_->prepare("INSERT INTO stock_movements(id,product_id,batch_id,type,quantity,original_unit,reason,balance_after,performed_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)");movement.bind(1,uuid());movement.bind(2,receipt.productId);if(batchId.isEmpty())movement.bindNull(3);else movement.bind(3,batchId);movement.bind(4,"purchase");movement.bind(5,receipt.quantity);movement.bind(6,receipt.enteredUnit);movement.bind(7,"Stock received");movement.bind(8,previous+receipt.quantity);movement.bind(9,receipt.performedBy);movement.bind(10,utcNow());movement.execute();tx.commit();
}
} // namespace pos
